### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Mike-bel** [WalletConnect/WalletConnectKotlinV2#1044]
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Lcom/walletconnect/android/internal/common/model/Redirect;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/walletconnect/android/internal/common/model/AppMetaData; or its super classes (declaration of 'com.walletconnect.android.internal.common.model.AppMetaData' appears in /data/app/ai.ave.platform-Tq-ZlXpbizRYMdkQzTTzHA==/base.apk!classes30.dex)
        at com.walletconnect.sign.engine.model.mapper.EngineMapperKt.toSessionProposeRequest(EngineMapper.kt:83)
        at com.walletconnect.sign.engine.domain.SignEngine.approve$sign_release(SignEngine.kt:301)
        at com.walletconnect.sign.client.SignProtocol.approveSession(SignProtocol.kt:130)
        at com.walletconnect.sign.client.SignClient.approveSession(Unknown Source:17)
        at com.walletconnect.web3.wallet.client.Web3Wallet.approveSession(Web3Wallet.kt:114)

**Comment by TalhaAli00** [comment]
@Mike-bel 
Can you provide some details as PR our template about your setup?

**Comment by Mike-bel** [comment]
> @Mike-bel Can you provide some details as PR our template about your setup?

thanks, I Re edited the issue and provided a detailed description.

**Comment by maciejkrolik** [comment]
Same issue :( Works as expected with BOM 1.13.1
