### ISSUE TITLE
ParametrizedType illegalArgumentException when using minify.

### ISSUE THREAD

**Issue by jchau207** [WalletConnect/WalletConnectKotlinV2#1056]
**Describe the bug**
A crash happens on CoreClient() init io runtime when minify set to true.

- This issue does not happen when minify is turned off. 

```
Caused by: java.lang.IllegalArgumentException: Receive method must return ParameterizedType: public abstract kotlinx.coroutines.flow.Flow com.walletconnect.foundation.network.data.service.RelayService.observeBatchSubscribeAcknowledgement()
                                                                                                    	at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(ServiceMethod.kt:74)
                                                                                                    	at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(ServiceMethod.kt:66)
                                                                                                    	at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.toServiceMethod(ServiceMethodExecutor.kt:47)
                                                                                                    	at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.findServiceMethods(ServiceMethodExecutor.kt:38)
                                                                                                    	at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.create(ServiceMethodExecutor.kt:32)
                                                                                                    	at com.tinder.scarlet.internal.Service$Factory.create(Service.kt:28)
                                                                                                    	at com.tinder.scarlet.Scarlet.implementService(Scarlet.kt:108)
                                                                                                    	at com.tinder.scarlet.Scarlet.create(Scarlet.kt:100)
                                                                                                    	at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$12.invoke(CoreNetworkModule.kt:124)
                                                                                                    	at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$12.invoke(CoreNetworkModule.kt:123)
                                                                                                    	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
                                                                                                    	... 34 more
```

**SDK Version**
 - Kotlin
 - com.walletconnect:android-core:1.16.1

**To Reproduce**
1. Enable Minify
2. Initialize CoreClient: `com.walletconnect.android.CoreClient.initialize`

**Expected behavior**
 No crash should happen

**Device (please complete the following information):**
 - Android 12, AGP 8.0

**Comment by jchau207** [comment]
@jakubuid 

I upgraded to the Core SDK to `1.19.0` now i am getting this error:

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.walletconnect.android.CoreInterface" 
```

with or without minify turned on.
