### ISSUE TITLE
 Pairing timeout error: Timed out waiting for 5000 ms

### ISSUE THREAD

**Issue by Yonghengl** [WalletConnect/WalletConnectKotlinV2#1093]
I am using the latest demo on the[ Pixel 4a (Android version 13)]mobile phone, connecting to https://react-app.walletconnect.com/, an error occurs, and MetaMask can be linked on this mobile phone
  
  Demo:
  https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/sample/wallet

Error:
 getPairing Error(throwable=java.lang.Throwable: Pairing timeout error: Timed out waiting for 5000 ms)

**Comment by jtomtan** [comment]
> I am using the latest demo on the[ Pixel 4a (Android version 13)]mobile phone, connecting to https://react-app.walletconnect.com/, an error occurs, and MetaMask can be linked on this mobile phone
> 
> Demo: https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/sample/wallet
> 
> Error: getPairing Error(throwable=java.lang.Throwable: Pairing timeout error: Timed out waiting for 5000 ms)

Hi, Yonghengl

Same issue here. What about now? Have you guys figured out the problem?

**Comment by bigman212** [comment]
> > I am using the latest demo on the[ Pixel 4a (Android version 13)]mobile phone, connecting to https://react-app.walletconnect.com/, an error occurs, and MetaMask can be linked on this mobile phone
> > Demo: https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/sample/wallet
> > Error: getPairing Error(throwable=java.lang.Throwable: Pairing timeout error: Timed out waiting for 5000 ms)
> 
> Hi, Yonghengl
> 
> Same issue here. What about now? Have you guys figured out the problem?
@jtomtan @Yonghengl 
This problem occurs when the RelayClient from the Web3Wallet can't or doesn't try to open the WS connection to the relay server. 
I have fixed it with switching `connectionType` to `ConnectionType.MANUAL` and opening WS connection by myself like this:
```kotlin
        val projectId = "..."
        val relayUrl = "relay.walletconnect.com"
        val appMetaData = Core.Model.AppMetaData(...)

        CoreClient.initialize(
            relayServerUrl =  "wss://$relayUrl?projectId=${projectId}",
            connectionType =  ConnectionType.MANUAL, // <----
            application = application,
            metaData = appMetaData,
            onError = { Timber.e(it.throwable) }
        )

        Web3Wallet.initialize(
            params = Wallet.Params.Init(core = CoreClient),
            onSuccess = {
                CoreClient.Relay.connect { error: Core.Model.Error -> Timber.e(error.throwable) } // try to connect to Relay server
            },
            onError = { Timber.e(it.throwable, "Web3Wallet.initialize failed") }
        )
```

**Comment by jakubuid** [comment]
Can we close this issue?

**Comment by hamberluo** [comment]
> I am using the latest demo on the[ Pixel 4a (Android version 13)]mobile phone, connecting to https://react-app.walletconnect.com/, an error occurs, and MetaMask can be linked on this mobile phone
> 
> Demo: https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/sample/wallet
> 
> Error: getPairing Error(throwable=java.lang.Throwable: Pairing timeout error: Timed out waiting for 5000 ms)

check your device time first.
in my case, pixel device time is not correct.

**Comment by jasonwyatt** [comment]
We just saw this happen in the wild on a user's device as well.  Seemed to happen after the user opted to reject the session.

Device info:
Xiaomi Redmi 12C
Android 13

```
Fatal Exception: java.lang.Throwable: Pairing timeout error: Timed out waiting for 5000 ms
       at com.walletconnect.android.pairing.client.PairingProtocol$pair$1$2.invoke(PairingProtocol.kt:74)
       at com.walletconnect.android.pairing.client.PairingProtocol$pair$1$2.invoke(PairingProtocol.kt:60)
       at com.walletconnect.android.pairing.client.PairingProtocol.awaitConnection(PairingProtocol.kt:133)
       at com.walletconnect.android.pairing.client.PairingProtocol.access$getKoinApp$p(PairingProtocol.kt:20)
       at com.walletconnect.android.pairing.client.PairingProtocol.access$awaitConnection(PairingProtocol.kt:20)
       at com.walletconnect.android.pairing.client.PairingProtocol$awaitConnection$1.invokeSuspend(PairingProtocol.kt)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by jakubuid** [comment]
fixed with BOM_1.31.3
