### ISSUE TITLE
Getting older sessionRequest and data even if send new request

### ISSUE THREAD

**Issue by aadityapaliwal** [WalletConnect/WalletConnectKotlinV2#1105]
**Describe the bug**
I am getting older sessionRequest data on onSessionRequest callback and that too multiple time. Even after I disconnect and connect with new QR code, it's sending older data.

**SDK Version**
 - implementation("com.walletconnect:android-core")
 -  implementation("com.walletconnect:web3wallet")
 - implementation(platform("com.walletconnect:android-bom:1.15.0"))

**To Reproduce**
1. Pair a dapp with your wallet
2. It will start sending getNetwork, getMirrorNetwork, call events even if you didn't requested for.
3. Send a new request from your dapp with a different accountid
4. Now onSessionRequest, I am getting older request though.

**Expected behavior**
It should update new request and data.

**Screenshots**

**Device (please complete the following information):**
 - Device: Motorola G5
 - OS: Android 8.1.0
 - Browser [e.g. stock browser, chrome]

**Additional context**
This is the older request and data.
```
This is request I am getting ->

SessionRequest(topic=fde7b0aab07605ef2bd219e56c9e4084558a667c6f95629c4c768b6f71b7f9cd, chainId=hedera:296, peerMetaData=AppMetaData(name=Blade Wallet Demo App, description=, url=https://127.0.0.1:3001, icons=[], redirect=, verifyUrl=null), request=JSONRPCRequest(id=1692698541921573, method=call, params={"accountId":"0.0.622648","executable":"Sg4KAhAAEggIABAAGLiAJg==","isTransaction":false}))

This is the dapp with which I am currently paired with. You can check the topic is different with above sessionRequest ->

[Session(pairingTopic=2a862d0b52b8bb7ffafa14e5a9745269704d592602cd36676501113ee0218297, topic=838576a3c283721b88dc950708efed4ac9059774f7239a8d48d9ee396b23d36b, expiry=1693393463, requiredNamespaces={hedera=Proposal(chains=[hedera:296], methods=[signTransaction, call, getAccountBalance, getAccountInfo, getLedgerId, getAccountId, getAccountKey, getNetwork, getMirrorNetwork, sign, getAccountRecords, checkTransaction, populateTransaction], events=[accountsChanged, walletUnlocked, walletLocked])}, optionalNamespaces={}, namespaces={hedera=Session(chains=[hedera:296], accounts=[hedera:296:0.0.622648], methods=[signTransaction, call, getAccountBalance, getAccountInfo, getLedgerId, getAccountId, getAccountKey, getNetwork, getMirrorNetwork, sign, getAccountRecords, checkTransaction, populateTransaction], events=[accountsChanged, walletUnlocked, walletLocked])}, metaData=AppMetaData(name=Blade Wallet Demo App, description=, url=https://127.0.0.1:3001, icons=[], redirect=, verifyUrl=null))]
```

**Comment by jakubuid** [comment]
Hey @aadityapaliwal thanks for reporting. Couple of questions from my side to understand your problem better:
- What happens when you reject the old session request? Can you see the correct one eventually after rejecting all the old ones?
- Can you share the dapp's link that you use for testing? Would like to try to reproduce it.
-Can you see this error on older web3wallet SDK versions?

**Comment by aadityapaliwal** [comment]
@jakubuid Thanks for revert back.

1. How can I reject old sessionRequest once I approved a new session proposal. If I tries to respond the older topic id, it's throwing me this error - 

> Error(throwable=com.walletconnect.android.internal.common.exception.CannotFindSequenceForTopic: Cannot find sequence for given topic: 2fb15c4400fa2f7a4773ac96b158f377000ddd55e4c7499e4f407d2956a7b934)


2. I am using this Dapp - http://dropp-walletconnect-testbed.s3-website-us-east-1.amazonaws.com/.

3. I downgraded com.walletconnect:android-bom to 1.14.0 but getting exception and result in crashing the app https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1044. I further downgraded it to 1.13.1 and it's working fine. I am getting correct topic id in the sessionRequest.

4. Yes, once I uninstall the wallet and install a fresh one, then I get the correct new topic ID but if I again pair it with new topic id then same issue arises.

So, it seems working fine with bom v1.13.1. Should I downgrade it?

**Comment by jakubuid** [comment]
Thanks for the reply.
I think I know what the root cause is - I'm working on the fix and we're aiming to release a new version this/early next week

**Comment by nguyennh-0786** [comment]
@jakubuid when we will release this version?

**Comment by aadityapaliwal** [comment]
@jakubuid I have updated the library on the latest version 1.16.0 and tried it but still getting the older requests. It seems like it's sending the older request which I might have sent few minutes back. Then even if I request the new one for sign transaction, it's sending older. getMirrorNetwork, getNetwork requests are coming as older topic.

```
This is the active session - 
2023-09-06 15:46:56.439 20518-20518 Active sessions D  [Session(pairingTopic=7adf779063d7cab770a62b59221f2ba2a9c6eacaf8a704d39547a089b1b42467, topic=d10f95558829c1fbfda293e3467957e142588499566070e8e27f73f6f697be89, expiry=1694599111, requiredNamespaces={hedera=Proposal(chains=[hedera:296], methods=[signTransaction, call, getAccountBalance, getAccountInfo, getLedgerId, getAccountId, getAccountKey, getNetwork, getMirrorNetwork, sign, getAccountRecords, checkTransaction, populateTransaction], events=[accountsChanged, walletUnlocked, walletLocked])}, optionalNamespaces={}, namespaces={hedera=Session(chains=[hedera:296], accounts=[hedera:296:0.0.622648], methods=[signTransaction, call, getAccountBalance, getAccountInfo, getLedgerId, getAccountId, getAccountKey, getNetwork, getMirrorNetwork, sign, getAccountRecords, checkTransaction, populateTransaction], events=[accountsChanged, walletUnlocked, walletLocked])}, metaData=AppMetaData(name=Blade Wallet Demo App, description=, url=https://dropp-walletconnect-testbed.s3.amazonaws.com, icons=[], redirect=, verifyUrl=null))]
```

```
2023-09-06 15:48:01.032 20518-20802 onSessionRequest  D topic af74589c92a296c8f47a1155203ced12b77ff9d030fa3a2b405b4835d4934bab request JSONRPCRequest(id=1693993557098647, method=getMirrorNetwork, params={"accountId":"0.0.622648"})
```

> This error is throwing when I respond to the previous request

FATAL EXCEPTION: DefaultDispatcher-worker-9
                                                                                                    Process: PID: 20164
                                                                                                    com.walletconnect.android.internal.common.exception.CannotFindSequenceForTopic: Cannot find sequence for given topic: 22ce7f8821630e35a0d0c705b5abc351280de3b68ecd00c012a98db92678e61d
                                                                                                    	at com.walletconnect.sign.engine.use_case.calls.RespondSessionRequestUseCase$respondSessionRequest$2.invokeSuspend(RespondSessionRequestUseCase.kt:49)
                                                                                                    	at com.walletconnect.sign.engine.use_case.calls.RespondSessionRequestUseCase$respondSessionRequest$2.invoke(Unknown Source:8)
                                                                                                    	at com.walletconnect.sign.engine.use_case.calls.RespondSessionRequestUseCase$respondSessionRequest$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
                                                                                                    	at com.walletconnect.sign.engine.use_case.calls.RespondSessionRequestUseCase.respondSessionRequest(RespondSessionRequestUseCase.kt:46)
                                                                                                    	at com.walletconnect.sign.engine.domain.SignEngine.respondSessionRequest(Unknown Source:7)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$respond$1.invokeSuspend(SignProtocol.kt:213)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by nguyennh-0786** [comment]
@jakubuid Please reopen this issue

**Comment by jakubuid** [comment]
@aadityapaliwal @nguyennh-0786 
How can we reproduce this issue? Can you provide the steps?
Can you try disconnecting from all the active sessions and try again?

**Comment by aadityapaliwal** [comment]
@jakubuid I did try disconnecting with all sessions but it's still sending the old requests.

I am using the Motorola Moto G5 Android version 8.1.0 (API Level 27). Please use the below steps to repro it -

- Navigate to https://dropp-walletconnect-testbed.s3.amazonaws.com/index.html
- Copy the URI from copy to clipboard and send it in your device.
- Connect wallet with URI.
- It will ask to approve the request and open a page. Tap on Approve.
- As soon as I approve it, I have started getting sessionRequest from Dapp for getNetwork and getMirrorNetwork. 
- Now go to above Dapp and send any request.
- You will get the new request. Now disconnect with that dapp.
- Reconnect with the same Dapp and send a new sign request from Dapp.
- Now If you check the logs it will send the older request again.

Check my active session and onSessionRequest logs in the above comment.

**Comment by jakubuid** [comment]
Hey @aadityapaliwal thank you for your patience
I was trying to reproduce this issue but I don't have access to [dropp-walletconnect-testbed.s3.amazonaws.com/index.html](https://dropp-walletconnect-testbed.s3.amazonaws.com/index.html) in order to connect. Can you help with it?

**Comment by aadityapaliwal** [comment]
@jakubuid Please try this - https://dropp-walletconnect-testbed.dropp.cc/

**Comment by jakubuid** [comment]
So it seems the problem is that the requests sent from dapp to wallet are not responded to. Meaning that the user neither approved nor rejected them. 

In the SDK we keep all the not responded session requests in a queue to prevent any request from being lost. The mechanism will keep emitting the first not responded session request from the queue until it expires or the user responds. Every new request is added to the end of the queue and triggers the first one.

If you need to send sth from dapp to wallet that doesn't require user interaction, I'd recommend using the emit method that emits events that you agreed on during session negotiation.

**Comment by aadityapaliwal** [comment]
@jakubuid Thanks for the description. I got the point of having mechanism for the not responded request but if we disconnect with that topic, then it shouldn't send the not responded request of the older topic, isn't it?

**Comment by jakubuid** [comment]
Yes, you're right. I'll look deeper into that

**Comment by muratogat** [comment]
Exactly, the problem is that request over an already disconnected session can't be responded, so they are stuck in the queue forever.

> The mechanism will keep emitting the first not responded session request from the queue until it expires or the user responds. Every new request is added to the end of the queue and triggers the first one.

I understand the motivation behind not losing requests, but is this a good trade-off? Especially since this is triggered by the user activaly initiating another request. What are the chances that the user wants to Approve/Reject a potentially days-old request, vs. the user mistakenly approving an unwanted request they ignored some days ago because they thought the approve dialog was related to the tx they just initiated? Wouldn't it be much safer to assume any request older than some minutes (or 1h if you want to be safe) is rejected? The problem is that from the UX perspective, ignoring or rejecting a request has the same outcome, but you treat it differently.

**Comment by jakubuid** [comment]
So the key problem is why you still see session requests from disconnected sessions. This is what I'll try to reproduce. The team will also reconsider this approach. Thanks!
