### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed

### ISSUE THREAD

**Issue by let-it-snow** [WalletConnect/WalletConnectKotlinV2#1192]
Hi,
Crashlytics reports some kind of crashes (I think related to the [issue](https://github.com/WalletConnect/WalletConnectKotlinV2/issues/859))

**Entry point:**
`CoreClient.initialize(...)`

**Stacktrace:**

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ecEf_7317GqABJO1tepr5g==/com.app-WWYl7TTrceT24h2sRTX4TQ==/lib/arm64/libsqlcipher.so" has bad ELF magic: 00000000
       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
       at java.lang.System.loadLibrary(System.java:1661)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
       at com.squareup.sqldelight.android.AndroidSqliteDriver.<init>(AndroidSqliteDriver.kt:56)
       at com.squareup.sqldelight.android.AndroidSqliteDriver.<init>(AndroidSqliteDriver.kt:46)
       at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:181)
       at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:180)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.kt:133)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:26)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke(BaseStorageModule.kt:23)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.access$invoke$createCoreDB(BaseStorageModule.kt:23)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:71)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:69)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.kt:133)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:82)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:82)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.kt:133)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$11.invoke(BaseStorageModule.kt:88)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$11.invoke(BaseStorageModule.kt:88)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.kt:133)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:9)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:9)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.kt:133)
       at com.walletconnect.android.pairing.client.PairingProtocol.initialize(PairingProtocol.kt:26)
       at com.walletconnect.android.CoreProtocol.initialize(CoreProtocol.kt:92)
       at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:1)
       at com.walletconnect.android.CoreInterface$DefaultImpls.initialize$default(CoreInterface.kt:25)
       ...
       at CoreClient.initialize(...)
```

**BOM:** v1.17.2
**Device:** Xiaomi Mi 11 X
**OS:** Android 13
**Kotlin:** 1.9.10
**AGP:** 8.1.2
**BC in App:** 1.71

**Comment by muratogat** [comment]
+1
Please fix. Top crash on Firebase currently for my app.
Seeing on Android 8, Android 12.

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.aktionariat.app-RPv3WMi83L7GGzjr35MY4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.aktionariat.app-RPv3WMi83L7GGzjr35MY4Q==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.walletconnect.android.di.CoreStorageModuleKt.loadSqlCipherLibrary(CoreStorageModule.kt:165)
       at com.walletconnect.android.di.CoreStorageModuleKt.getSupportFactory(CoreStorageModule.kt:158)
       at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:185)
       at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:180)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:617)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.access$invoke$createCoreDB(BaseStorageModule.kt:24)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:72)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:70)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:105)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:83)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$11.invoke(BaseStorageModule.kt:105)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$11.invoke(BaseStorageModule.kt:89)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:17)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:9)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at com.walletconnect.android.pairing.client.PairingProtocol.initialize(PairingProtocol.kt:148)
       at com.walletconnect.android.CoreProtocol.initialize(CoreProtocol.kt:92)
       at com.walletconnect.android.CoreClient.initialize(:39)
       at com.walletconnect.android.CoreInterface$DefaultImpls.initialize$default(CoreInterface.kt:25)
       at com.aktionariat.app.service.wc2service.WC2Connector.onAppStart(WC2Connector.kt:63)
       at com.aktionariat.app.AktionariatApp.onCreate(AktionariatApp.kt:29)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by NilayTheAndroidGuy** [comment]
Facing the same issue. Any solutions to this?

**Comment by kacperoak** [comment]
Are you using the latest SDK version?

**Comment by kamilargent** [comment]
Looks like this is still an issue. We switched our artifact from APK to AAB and this issue started to happen for us as well (crash on app startup). 

BOM: v1.32.1
Device: Nexus 5x
OS: Android 8.1.0

@jakubuid could you please take a look at that issue again

```
          Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/im.argent.contractwalletclient-HytmBbxzZuRJkDYxd9kQCA==/base.apk"],nativeLibraryDirectories=[/data/app/im.argent.contractwalletclient-HytmBbxzZuRJkDYxd9kQCA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.walletconnect.android.di.CoreStorageModuleKt.loadSqlCipherLibrary(CoreStorageModule.kt:170)
       at com.walletconnect.android.di.CoreStorageModuleKt.getSupportFactory(CoreStorageModule.kt:163)
       at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:190)
       at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:185)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
       at org.koin.core.scope.Scope.get(Scope.kt:213)
       at org.koin.core.scope.Scope.get$default(Scope.kt:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:32)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:34)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:35)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:38)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:41)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke(BaseStorageModule.kt:29)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.access$invoke$createCoreDB(BaseStorageModule.kt:29)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:80)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:78)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
       at org.koin.core.scope.Scope.get(Scope.kt:213)
       at org.koin.core.scope.Scope.get$default(Scope.kt:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:101)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:101)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:101)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
       at org.koin.core.scope.Scope.get(Scope.kt:213)
       at org.koin.core.scope.Scope.get$default(Scope.kt:136)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$13.invoke(BaseStorageModule.kt:111)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$13.invoke(BaseStorageModule.kt:111)
       at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$13.invoke(BaseStorageModule.kt:111)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
       at org.koin.core.scope.Scope.get(Scope.kt:213)
       at org.koin.core.scope.Scope.get$default(Scope.kt:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:12)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:13)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:14)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:15)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:16)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:17)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:18)
       at org.koin.core.scope.Scope.get$default(Scope.java:136)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:19)
       at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:10)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
       at org.koin.core.scope.Scope.get(Scope.kt:213)
       at org.koin.core.scope.Scope.get$default(Scope.kt:136)
       at com.walletconnect.android.pairing.client.PairingProtocol.initialize(PairingProtocol.kt:32)
       at com.walletconnect.android.CoreProtocol.initialize(CoreProtocol.kt:113)
       at com.walletconnect.android.CoreClient.initialize(CoreClient.kt)
       at com.walletconnect.android.CoreInterface$DefaultImpls.initialize$default(CoreInterface.kt:27)

```

**Comment by willgzn** [comment]
Also getting this error on the same device apparently but I suspect that it could happen to more devices.

BOM: v1.35.1
Device: Nexus 5x
OS: Android 8.1.0
