### ISSUE TITLE
NoSuchMethodError when open Web3Modal

### ISSUE THREAD

**Issue by xemniz** [WalletConnect/WalletConnectKotlinV2#1299]
**Describe the bug**
I have this error when trying to open modal sheet
java.lang.NoSuchMethodError: No virtual method getBackQueue()Lkotlin/collections/ArrayDeque; in class Landroidx/navigation/NavController; or its super classes (declaration of 'androidx.navigation.NavController' appears in /data/app/~~EhdRHUGllLoB-BzAZgrPjQ==/io.interfacelab.debug-m78d9nwRSf09VvJSFTG06Q==/base.apk!classes18.dex)
at com.walletconnect.web3.modal.ui.components.internal.root.Web3ModalRootState.getCanPopUp(Web3ModalRootState.kt:32)
at com.walletconnect.web3.modal.ui.components.internal.root.Web3ModalRootKt.TopBarStartIcon(Web3ModalRoot.kt:105)
at com.walletconnect.web3.modal.ui.components.internal.root.Web3ModalRootKt.access$TopBarStartIcon(Web3ModalRoot.kt:1)

**SDK Version**
 - Client: Kotlin
 - Version bom 1.22.0

**To Reproduce**
navController.openWeb3Modal(
                        shouldOpenChooseNetwork = true,
                        onError = { }
                    )

**Expected behavior**
Doesn't crash

**Device (please complete the following information):**
 - Device: [Oneplus 8 pro]
 - OS: [Android 11]

**Comment by kacperoak** [comment]
What version of navigation dependencies do you have in your project?

**Comment by xemniz** [comment]
2.7.6

**Comment by Raenar4k** [comment]
Same issue.
Version bom 1.22.0
We don't even have navigation dependency declared.
I've used Web3ModalComponent:
```
    Web3ModalComponent(
        shouldOpenChooseNetwork = true,
        closeModal = { }
    )
```

This happens because other library also uses navigation library, but uses more modern version, which is then applied to web3modal:
```
+--- com.walletconnect:web3modal -> 1.1.1
|    +--- androidx.navigation:navigation-fragment-ktx:2.5.3 -> 2.7.6
```

@kacperoak Is it possible for Wallet Connect to update navigation library version? I think its reasonable thing to do.
Version 2.5.3 was realeased on October 24, 2022.

**Comment by Raenar4k** [comment]
@jakubuid Hi. Any update on that? As this is blocker for us - we are still using handmade UI + Sign SDK for this, and cannot begin migration to Modal SDK until this is resolved

**Comment by jakubuid** [comment]
@Raenar4k Hello, I'll work on the update of navigation lib version

**Comment by jakubuid** [comment]
@Raenar4k the `androidx.navigation:navigation-fragment-ktx` is already on `2.7.7` within the newest SDK version. I'll update it further to `2.8.0` tho
