### ISSUE TITLE
IllegalStateException: ChaCha20Poly1305 cannot be reused for encryption during dapp session disconnect.

### ISSUE THREAD

**Issue by jasonwyatt** [WalletConnect/WalletConnectKotlinV2#1304]
**Describe the bug**
A fatal exception is thrown while disconnecting from a dapp session.

**SDK Version**
 - Client: Kotlin
 - Version: BOM version 1.20.0

**To Reproduce**
1. Disconnect from an active dapp session.

See this stack trace:

```
Fatal Exception: java.lang.IllegalStateException: ChaCha20Poly1305 cannot be reused for encryption
       at org.bouncycastle.crypto.modes.ChaCha20Poly1305.checkData(ChaCha20Poly1305.java)
       at org.bouncycastle.crypto.modes.ChaCha20Poly1305.doFinal(ChaCha20Poly1305.java)
       at com.walletconnect.android.internal.common.crypto.codec.ChaChaPolyCodec.encryptPayload-THFQ7Pg(ChaChaPolyCodec.kt:144)
       at com.walletconnect.android.internal.common.crypto.codec.ChaChaPolyCodec.encryptEnvelopeType0(ChaChaPolyCodec.kt:103)
       at com.walletconnect.android.internal.common.crypto.codec.ChaChaPolyCodec.encrypt(ChaChaPolyCodec.kt:42)
       at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.publishJsonRpcRequest(JsonRpcInteractor.kt:87)
       at com.walletconnect.android.internal.common.model.type.JsonRpcInteractorInterface$DefaultImpls.publishJsonRpcRequest$default(JsonRpcInteractorInterface.kt:23)
       at com.walletconnect.sign.engine.use_case.calls.DisconnectSessionUseCase$disconnect$2.invokeSuspend(DisconnectSessionUseCase.kt:34)
       at com.walletconnect.sign.engine.use_case.calls.DisconnectSessionUseCase$disconnect$2.invoke(DisconnectSessionUseCase.kt)
       at com.walletconnect.sign.engine.use_case.calls.DisconnectSessionUseCase$disconnect$2.invoke(DisconnectSessionUseCase.kt)
       at com.walletconnect.sign.engine.use_case.calls.DisconnectSessionUseCase$disconnect$2.invoke(DisconnectSessionUseCase.kt)
       at com.walletconnect.sign.engine.use_case.calls.DisconnectSessionUseCase$disconnect$2.invoke(DisconnectSessionUseCase.kt)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
       at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
       at com.walletconnect.sign.engine.use_case.calls.DisconnectSessionUseCase.disconnect(DisconnectSessionUseCase.kt:23)
       at com.walletconnect.sign.engine.domain.SignEngine.disconnect(SignEngine.kt)
       at com.walletconnect.sign.client.SignProtocol$disconnect$1.invokeSuspend(SignProtocol.kt:308)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.CoroutineContextKt.withContinuationContext(CoroutineContext.kt:108)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:90)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Expected behavior**
A fatal exception is not thrown.

**Device (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 14
 - Browser: n/a
 - Version: n/a

**Comment by jakubuid** [comment]
@jasonwyatt it looks like stack trace is truncated, we cannot see the actual exception, please edit 🙏

**Comment by jasonwyatt** [comment]
I've updated the bug to include the first line. It was hidden because it was on the same line as the opening ``` of the code block.
