### ISSUE TITLE
om.walletconnect.foundation.network.BaseRelayClient get time out and exception

### ISSUE THREAD

**Issue by mahdit8** [WalletConnect/WalletConnectKotlinV2#1334]
**Describe the bug**
On some users we got it exception:

```
java.lang.Throwable: Publish request timed out: Timed out waiting for 10000 ms
        at com.walletconnect.foundation.network.BaseRelayClient$observePublishResult$1.invokeSuspend(BaseRelayClient.kt:114)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
And the thread lead to this exception is:

`Thread 318 - DefaultDispatcher-worker-18 - (RUNNABLE)         at com.walletconnect.foundation.network.BaseRelayClient$observePublishResult$1.invokeSuspend(BaseRelayClient.kt:114)         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)         at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)         at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`

**SDK Version**
 - Client: Kotlin
 - SDK:
     implementation(platform("com.walletconnect:android-bom:1.22.2"))
     implementation("com.walletconnect:android-core")
     implementation("com.walletconnect:web3wallet")

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. Pixel]
 - OS: [e.g. Android 12]
 - Browser [e.g. stock browser, chrome]

**Additional context**

**Comment by nguyennh-0786** [comment]
I have the same issue. My device is `Moto G52j 5G - Android 12`

**Comment by jakubuid** [comment]
Hey! This should be resolved with BOM_1.23. Can you please update and check? 🙏

**Comment by TalhaAli00** [comment]
@nguyennh-0786 
Following up to see if you've had a chance to test the latest version of the SDK
