### ISSUE TITLE
java.lang.IllegalStateException: Creating Pairing failed

### ISSUE THREAD

**Issue by dora4** [WalletConnect/WalletConnectKotlinV2#1347]
**Describe the bug**
Android app crash log.
FATAL EXCEPTION: main
Process: com.dorachat.privacybox, PID: 9090
java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: com.walletconnect.android.internal.common.exception.NoRelayConnectionException: Connection error: Please check your Internet connection
	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.checkConnectionWorking(JsonRpcInteractor.kt:72)
	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.subscribe(JsonRpcInteractor.kt:252)
	at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:126)
	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:46)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.generatePairing(ParingController.kt:55)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getPairing(ParingController.kt:27)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getUri(ParingController.kt:53)
	at com.walletconnect.web3.modal.ui.routes.connect.ConnectViewModel.getUri(Unknown Source:2)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:113)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:106)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:855)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:703)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:96)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1436)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1388)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1328)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl$generatePairing$1.invoke(ParingController.kt:56)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl$generatePairing$1.invoke(ParingController.kt:55)
	at com.walletconnect.android.pairing.client.PairingProtocol$create$1.invoke(PairingProtocol.kt:46)
	at com.walletconnect.android.pairing.client.PairingProtocol$create$1.invoke(PairingProtocol.kt:46)
	at com.walletconnect.android.pairing.engine.domain.PairingEngine$create$1$2.invoke(PairingEngine.kt:130)
	at com.walletconnect.android.pairing.engine.domain.PairingEngine$create$1$2.invoke(PairingEngine.kt:126)
	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.subscribe(JsonRpcInteractor.kt:254)
	at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:126)
	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:46)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.generatePairing(ParingController.kt:55)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getPairing(ParingController.kt:27)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getUri(ParingController.kt:53)
	at com.walletconnect.web3.modal.ui.routes.connect.ConnectViewModel.getUri(Unknown Source:2)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:113)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:106)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:855)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:703)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:96)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1436)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1388)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1328)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl$generatePairing$1.invoke(ParingController.kt:56)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl$generatePairing$1.invoke(ParingController.kt:55)
	at com.walletconnect.android.pairing.client.PairingProtocol$create$1.invoke(PairingProtocol.kt:46)
	at com.walletconnect.android.pairing.client.PairingProtocol$create$1.invoke(PairingProtocol.kt:46)
	at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:140)
	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:46)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.generatePairing(ParingController.kt:55)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getPairing(ParingController.kt:27)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getUri(ParingController.kt:53)
	at com.walletconnect.web3.modal.ui.routes.connect.ConnectViewModel.getUri(Unknown Source:2)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:113)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:106)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:855)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:703)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:96)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1436)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1388)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1328)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl$generatePairing$1.invoke(ParingController.kt:56)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl$generatePairing$1.invoke(ParingController.kt:55)
	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:48)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.generatePairing(ParingController.kt:55)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getPairing(ParingController.kt:27)
	at com.walletconnect.web3.modal.ui.routes.connect.PairingControllerImpl.getUri(ParingController.kt:53)
	at com.walletconnect.web3.modal.ui.routes.connect.ConnectViewModel.getUri(Unknown Source:2)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:113)
	at com.walletconnect.web3.modal.ui.routes.connect.redirect.RedirectWalletScreenKt$RedirectWalletRoute$4.invoke(RedirectWalletScreen.kt:106)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:895)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:889)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)

**SDK Version**
 - Client: Kotlin
 - Version 1.22.0 and etc.

**To Reproduce**
1.Set Allowed Domains in https://cloud.walletconnect.com/, but do not use this domain name.
2.The application integrates the crash reporting module of Google Firebase
3.Then use the app to call the API that connects to the wallet

**Expected behavior**
No crash reported.

**Screenshots**
<img width="1140" alt="截屏2024-03-16 12 56 51" src="https://github.com/WalletConnect/WalletConnectKotlinV2/assets/71242257/8015e7d2-be6e-4bdd-85ce-2c50755a5f5c">

**Device (please complete the following information):**
 - Device: Medium Phone
 - OS: API 30

**Additional context**
My email address is dora924666990@gmail.com. Please let me know when the solution is solved.

**Comment by TalhaAli00** [comment]
Hello @dora4 
Looking into this issue's repro steps, you mention adding "Allowed Domains" but not using the domain. Do you mean your package name is different from the domain that you added? 

Also, going through the stacktrace, I see the root cause being that there wasn't an internet connection when you tried to create the pairing. Can you also verify if you're seeing this issue while you have a internet connection? We have a function `onConnectionStateChange` in the Delegate which will tell you the internet connection state.

**Comment by dora4** [comment]
I see that the domain mentioned in https://docs.walletconnect.com/cloud/relay#allowlist should not refer to the apk package name. This domain may be used for the website and should not be used in the app.

**Comment by dora4** [comment]
So if I set this domain, the pairing connection will not succeed in android sdk.

**Comment by TalhaAli00** [comment]
In the cloud application, you also have the ability to add your application/bundle IDs which will only allow those projects to use your project key. 
There is a [PR](https://github.com/WalletConnect/walletconnect-docs/pull/1504) to update the docs with this information.

Also, have you been able to test if you're still seeing your issue after verifying that the application is connected via the delegate?

**Comment by dora4** [comment]
I think the main reason is that mobile app should not set domain, so relayUrl will be invalid, like this
```kotlin
 val relayUrl = "dorachat.com"
 val serverUri = "wss://$relayUrl?projectId=${Environment.WALLET_CONNECT_PROJECT_ID}"
 val appMetaData = Core.Model.AppMetaData(
         name = getString(R.string.app_name),
         description = getString(R.string.app_description),
         url = "https://dorachat.com",
         icons = listOf("https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media"),
         redirect = "dorachat-modal-wc://request"
 )
```
As long as I don't set the domain, everything will be correct.

**Comment by dora4** [comment]
But I don't know if there will be any security risks in doing so.
