### ISSUE TITLE
After updating to 1.31.3 getting IllegalStateException: Unreadable ResponseBody!

### ISSUE THREAD

**Issue by rafaelekol** [WalletConnect/WalletConnectKotlinV2#1387]
When I try to connect using `CoreClient.Relay.connect()`, I am getting this crash log:

```
FATAL EXCEPTION: OkHttp Dispatcher
                 Process: io.example.wallet.dev, PID: 31172
                 java.lang.IllegalStateException: Unreadable ResponseBody! These Response objects have bodies that are stripped:
                  * Response.cacheResponse
                  * Response.networkResponse
                  * Response.priorResponse
                  * EventSourceListener
                  * WebSocketListener
                 (It is safe to call contentType() and contentLength() on these response bodies.)
                 	at okhttp3.internal.UnreadableResponseBody.read(-ResponseCommon.kt:49)
                 	at okio.RealBufferedSource.select(RealBufferedSource.kt:232)
                 	at okhttp3.internal._UtilJvmKt.readBomAsCharset(-UtilJvm.kt:89)
                 	at okhttp3.ResponseBody.string(ResponseBody.kt:72)
                 	at com.pandulapeter.beagle.logOkHttp.OkHttpInterceptor.intercept(OkHttpInterceptor.kt:63)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$7.invoke$lambda$0(CoreNetworkModule.kt:90)
                 	at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$7$$ExternalSyntheticLambda0.intercept(D8$$SyntheticClass:0)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$5.invoke$lambda$0(CoreNetworkModule.kt:75)
                 	at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$5$$ExternalSyntheticLambda0.intercept(D8$$SyntheticClass:0)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:533)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by rafaelekol** [comment]
@TalhaAli00 
I tried to debug issue, to find out the source of the problem. But I can't see your source code. I found old issue in your tracker: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/494
Can you check it and make it work.

**Comment by rafaelekol** [comment]
To test whether startup code in Application class is causing issue with WalletConnect I used `ConnectionType.MANUAL ` connection type. And called `CoreClient.Relay.connect()` manually after app launch. But it didn't help. Either I use `ConnectionType.AUTOMATIC` or  `ConnectionType.MANUAL ` SDK crashes with same error during connection. Below I will post our code related to WalletConnect.

Gradle file

```
implementation(platform("com.walletconnect:android-bom:1.31.3"))
implementation 'com.walletconnect:web3wallet'
implementation 'com.walletconnect:android-core'


//Ressolve conflicts with WalletConnect SDK and SolanaKit
configurations.all { c ->
    c.resolutionStrategy.dependencySubstitution {
        substitute module('org.bouncycastle:bcprov-jdk15on:1.65.01') using module('org.bouncycastle:bcprov-jdk18on:1.77')
        substitute module('org.bouncycastle:bcprov-jdk15on:1.70') using module('org.bouncycastle:bcprov-jdk18on:1.77')
        substitute module('org.bouncycastle:bcprov-jdk15on:1.66') using module('org.bouncycastle:bcprov-jdk18on:1.77')
        substitute module('org.bouncycastle:bcprov-jdk15to18:1.68') using module('org.bouncycastle:bcprov-jdk18on:1.77')
        substitute module('com.google.protobuf:protobuf-java:3.6.1') using module('com.google.protobuf:protobuf-javalite:3.21.1')
        substitute module('net.jcip:jcip-annotations:1.0') using module('com.github.stephenc.jcip:jcip-annotations:1.0-1')

        substitute module('com.tinder.scarlet:scarlet-core:0.1.12') using module('com.walletconnect.Scarlet:scarlet-core:1.0.1')
        substitute module('com.tinder.scarlet:scarlet:0.1.12') using module('com.walletconnect.Scarlet:scarlet:1.0.1')
        substitute module('com.tinder.scarlet:websocket-okhttp:0.1.12') using module('com.walletconnect.Scarlet:websocket-okhttp:1.0.1')
        substitute module('com.tinder.scarlet:stream-adapter-built-in:0.1.12') using module('com.walletconnect.Scarlet:stream-adapter-built-in:1.0.1')
        substitute module('com.tinder.scarlet:message-adapter-built-in:0.1.12') using module('com.walletconnect.Scarlet:message-adapter-built-in:1.0.1')
        substitute module('com.tinder.scarlet:lifecycle-android:0.1.12') using module('com.walletconnect.Scarlet:lifecycle-android:1.0.1')
    }
}
```

App.kt class
```
class App : Application() {
  override fun onCreate() {
      ...
      initializeWalletConnectV2(appConfig)
      ...
  }

private fun initializeWalletConnectV2(appConfig: AppConfigProvider) {
    val projectId = appConfig.walletConnectProjectId
    val serverUrl = "wss://${appConfig.walletConnectUrl}?projectId=$projectId"
    val connectionType = ConnectionType.AUTOMATIC
    val appMetaData = Core.Model.AppMetaData(
        name = appConfig.walletConnectAppMetaDataName,
        description = "",
        url = appConfig.walletConnectAppMetaDataUrl,
        icons = listOf(appConfig.walletConnectAppMetaDataIcon),
        redirect = null,
    )

    CoreClient.initialize(
        metaData = appMetaData,
        relayServerUrl = serverUrl,
        connectionType = connectionType,
        application = this,
        onError = { error ->
            Log.w("AAA", "error", error.throwable)
        },
    )
    Web3Wallet.initialize(Wallet.Params.Init(core = CoreClient)) { error ->
        Log.e("AAA", "error", error.throwable)
    }
}
}
```

**Comment by esedoi** [comment]
I also encountered the same problem, did you solve it?

**Comment by gemcoder21** [comment]
We did encounter such issue as well when using `loggingInterceptor 5.0.0`, but worked with  `loggingInterceptor 4.1.2`. No idea how they are connected, but something to do with interceptors
