### ISSUE TITLE
CoreClient.initialize failure in v Bom_1.31.4

### ISSUE THREAD

**Issue by abdrasulov** [WalletConnect/WalletConnectKotlinV2#1409]
**Describe the bug**

We are currently using v Bom_1.15.0. And we are trying to update to v Bom_1.31.4. But calling `CoreClient.initialize()` crashes app.

```
CoreClient.initialize(
    metaData = appMetaData,
    relayServerUrl = serverUrl,
    connectionType = connectionType,
    application = this,
    onError = { error ->
        Log.w("AAA", "error", error.throwable)
    },
)
```
The backtrace is as follows:

```
java.lang.NoSuchMethodError: No direct method <init>(Lapp/cash/sqldelight/db/SqlSchema;Landroid/content/Context;Ljava/lang/String;Landroidx/sqlite/db/SupportSQLiteOpenHelper$Factory;Landroidx/sqlite/db/SupportSQLiteOpenHelper$Callback;IZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lapp/cash/sqldelight/driver/android/AndroidSqliteDriver; or its super classes (declaration of 'app.cash.sqldelight.driver.android.AndroidSqliteDriver' appears in /data/app/~~BOsuBgZzO2gJC-8qaIMpbg==/io.horizontalsystems.bankwallet.dev-2Dly44Oo7coelFeDRTYNpw==/base.apk!classes25.dex)
at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:183)
at com.walletconnect.android.di.CoreStorageModuleKt$coreStorageModule$1$1.invoke(CoreStorageModule.kt:182)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
at org.koin.core.scope.Scope.get(Scope.kt:213)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.invoke$createCoreDB(BaseStorageModule.kt:698)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1.access$invoke$createCoreDB(BaseStorageModule.kt:27)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:75)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$5.invoke(BaseStorageModule.kt:73)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
at org.koin.core.scope.Scope.get(Scope.kt:213)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:122)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:96)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
at org.koin.core.scope.Scope.get(Scope.kt:213)
2024-05-27 16:13:33.961 26933-26933 AndroidRuntime          io.horizontalsystems.bankwallet.dev  E  	at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$12.invoke(BaseStorageModule.kt:122)
at com.walletconnect.android.internal.common.di.BaseStorageModuleKt$baseStorageModule$1$12.invoke(BaseStorageModule.kt:104)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
at org.koin.core.scope.Scope.get(Scope.kt:213)
at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:37)
at com.walletconnect.android.internal.common.di.CorePairingModuleKt$corePairingModule$1$1.invoke(CorePairingModule.kt:10)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
at org.koin.core.scope.Scope.get(Scope.kt:213)
at com.walletconnect.android.pairing.client.PairingProtocol.initialize(PairingProtocol.kt:179)
at com.walletconnect.android.CoreProtocol.initialize(CoreProtocol.kt:108)
at com.walletconnect.android.CoreClient.initialize(Unknown Source:39)
at com.walletconnect.android.CoreInterface$DefaultImpls.initialize$default(CoreInterface.kt:27)

```

**Comment by jakubuid** [comment]
Hey, thanks for reporting. Can you try with BOM_1.31.3? I'll help to narrow down the issue

**Comment by abdrasulov** [comment]
Hey. It crashes with the same error.

**Comment by vcoolish** [comment]
it's same for me after added another lib that uses sqldelight

**Comment by jakubuid** [comment]
@vcoolish does bumping SQLDelight resolve the crash?

**Comment by daniellfalcao** [comment]
I’m having the same problem. I’m using version 2.0.1 of SQLDelight, and when I downgraded to version 2.0.0 (the same used here in Wallet Connect), it started working again. Apparently, there is a breaking change from version 2.0.0 to 2.0.1 🫠 also forcing the version of SQLDelight used in Wallet Connect to 2.0.1 didn’t work for me.

**Comment by jakubuid** [comment]
@daniellfalcao would update sqldelight to 2.0.2 help with your crash?

**Comment by daniellfalcao** [comment]
No, I think you need to update your version, since the problem is using a version below 2.0.1 because everithing works here but when I try to use WalletConnect it fails on initialize with the same stacktrace from this issue.

**Comment by vcoolish** [comment]
> @vcoolish does bumping SQLDelight resolve the crash?

Yes, the versions in different libs should be synced. I set 2.0.0 temporarily in my other sdk

**Comment by jakubuid** [comment]
Thank you all - I'll go forward and merge a PR bumping SQLDelight to 2.0.2. It'll be available within the next release

**Comment by daniellfalcao** [comment]
https://github.com/cashapp/sqldelight/issues/4357#issuecomment-1946294813

And it's a critical update
