### ISSUE TITLE
Solana crash

### ISSUE THREAD

**Issue by mojjason** [WalletConnect/WalletConnectKotlinV2#1497]
**Describe the bug**
Web3Modal :  when i connect Solana chain ，Then I what to transfer sign , It crash 

**SDK Version**
 - Client: android kotlin
 - Version  com.walletconnect:android-bom:1.35.2  and com.reown:android-bom:1.0.0

**To Reproduce**
1. Go to 'ConnectButton  to connect solana chain --- success'
2. Click on 'web3Button report error'

**Crash Log maybe the reason is parsed data** 
FATAL EXCEPTION: main
java.lang.NumberFormatException: For input string: "ba2xjq"
at java.lang.Long.parseLong(Long.java:736)
at com.reown.appkit.ui.components.internal.commons.account.AccountImageKt.hexToRgb(AccountImage.kt:68)
at com.reown.appkit.ui.components.internal.commons.account.AccountImageKt.generateAvatarColors(AccountImage.kt:58)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButtonMixed$1$1$2$1$1.invoke-ek8zF_U(AccountButton.kt:142)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButtonMixed$1$1$2$1$1.invoke(AccountButton.kt:136)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at com.reown.appkit.ui.components.internal.commons.button.ButtonKt$ImageButton$1.invoke(Button.kt:76)
at com.reown.appkit.ui.components.internal.commons.button.ButtonKt$ImageButton$1.invoke(Button.kt:65)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:134)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:114)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:111)
at com.reown.appkit.ui.components.internal.commons.button.ButtonKt.ImageButton(Button.kt:62)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButtonMixed$1$1.invoke(AccountButton.kt:135)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButtonMixed$1$1.invoke(AccountButton.kt:118)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at com.reown.appkit.ui.components.internal.commons.SurfaceKt$TransparentSurface$1.invoke(Surface.kt:20)
at com.reown.appkit.ui.components.internal.commons.SurfaceKt$TransparentSurface$1.invoke(Surface.kt:19)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:134)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:114)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:111)
at com.reown.appkit.ui.components.internal.commons.SurfaceKt.TransparentSurface(Surface.kt:15)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButtonMixed$1.invoke(AccountButton.kt:118)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButtonMixed$1.invoke(AccountButton.kt:103)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
at com.reown.appkit.ui.theme.ThemeKt.ProvideAppKitThemeComposition(Theme.kt:14)
at com.reown.appkit.ui.components.button.AccountButtonKt.AccountButtonMixed(AccountButton.kt:103)
at com.reown.appkit.ui.components.button.AccountButtonKt.AccountButtonState(AccountButton.kt:86)
2024-09-27 15:36:34.413 28271-28271 AndroidRuntime com.blue.toothbrush E at com.reown.appkit.ui.components.button.AccountButtonKt.AccountButton(AccountButton.kt:71)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButton$2.invoke(Unknown Source:14)
at com.reown.appkit.ui.components.button.AccountButtonKt$AccountButton$2.invoke(Unknown Source:8)
at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1503)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513)
at android.view.Choreographer.doCallbacks(Choreographer.java:1128)
at android.view.Choreographer.doFrame(Choreographer.java:1037)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8503)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your request. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@mojjason 
Support.
  {c}2024

**Comment by benjamin029959** [comment]
@mojjason have you been able to resole this issue?
