### ISSUE TITLE
Demo wallet not pairing

### ISSUE THREAD

**Issue by rafaelekol** [WalletConnect/WalletConnectKotlinV2#224]
I am trying to run you demo wallet app. It opens, but when I try to pair to your https://react-app.walletconnect.com/, it throws following error.

```
22-06-22 12:20:39.482 26975-27008/com.walletconnect.wallet E/WalletConnectV2: Subscribe to topic: TopicVO(value=c648d85a8f2000c01ddf812756a08d2bf3909d58d1392abc3a7b95137465388a) error: java.lang.Throwable: Error code: -32601; Error message: Method not found
2022-06-22 12:20:39.483 26975-27008/com.walletconnect.wallet E/WalletConnectV2: java.lang.Throwable: Error code: -32601; Error message: Method not found
        at com.walletconnect.sign.network.data.client.RelayClient$observeSubscribeError$1$1.invokeSuspend(RelayClient.kt:134)
        at com.walletconnect.sign.network.data.client.RelayClient$observeSubscribeError$1$1.invoke(Unknown Source:8)
        at com.walletconnect.sign.network.data.client.RelayClient$observeSubscribeError$1$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at com.walletconnect.sign.network.data.adapter.FlowStreamAdapter$adapt$1.invokeSuspend(FlowStreamAdapter.kt:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by jakobuid** [comment]
Hey @rafaelekol, thanks for reporting. Our infra team is taking care of it.

**Comment by rafaelekol** [comment]
@jakobuid 

> please use beta-101 from master

how I should do this part?

**Comment by jakobuid** [comment]
Just follow the installation guide: https://github.com/WalletConnect/WalletConnectKotlinV2/tree/master#installation

**Comment by rafaelekol** [comment]
I use dependency in our project like this
implementation "com.github.WalletConnect:WalletConnectKotlinV2:1.0.0-beta101"

```
pairLink = wc:1fe199030f2b3e371edd90c55eeeb9afafa7b597df83586e08010cfd7d8b0e59@2?relay-protocol=waku&symKey=4165eaf71ed00330d0b916d943ea10c562a09274c1b6d88b8ac8e69e94c946fd
```
error
```
2022-06-22 16:31:30.936 23819-23819/io.horizontalsystems.bankwallet.dev E/WC2Service: pair error: 
    com.walletconnect.walletconnectv2.core.exceptions.client.WalletConnectException$GenericException: Error trying to create pairing. Validate URI
        at com.walletconnect.walletconnectv2.engine.domain.EngineInteractor.pair$walletconnectv2_release(EngineInteractor.kt:149)
        at com.walletconnect.walletconnectv2.client.SignProtocol.pair(SignProtocol.kt:107)
        at com.walletconnect.walletconnectv2.client.SignClient.pair(Unknown Source:12)
...
```

**Comment by jakobuid** [comment]
Hey issue is known and will be fixes within the next release. Thanks!
