### ISSUE TITLE
SignClient needs to be initialized first using the initialize function

### ISSUE THREAD

**Issue by jakobuid** [WalletConnect/WalletConnectKotlinV2#271]
**Describe the bug**
Given that user has installed a Kotlin Dapp and a Kotlin Wallet on his device. User opens the Kotlin Dapp, while the Kotlin Wallet is terminated. After choosing the network and pressing connect button, user clicks Deeplink button and redirects to the Kotlin Wallet.
After redirecting the Kotlin Wallet get crashed.

```
java.lang.IllegalStateException: SignClient needs to be initialized first using the initialize function
        at com.walletconnect.sign.client.SignProtocol.checkEngineInitialization(SignProtocol.kt:262)
        at com.walletconnect.sign.client.SignProtocol.pair(SignProtocol.kt:124)
        at com.walletconnect.sign.client.SignClient.pair(Unknown Source:12)
        at com.walletconnect.wallet.ui.accounts.AccountsViewModel.pair(AccountsViewModel.kt:23)
        at com.walletconnect.wallet.ui.accounts.AccountsFragment.onViewCreated(AccountsFragment.kt:36)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1467)
        at android.app.Activity.performStart(Activity.java:8082)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**SDK Version**
 - Client: Kotlin
 - Version: 2.0.0-rc.0

**To Reproduce**
1. Go to Kotlin Dapp. Install Kotlin Wallet. Have Kotlin Wallet terminated form device memory.
2. Click on connect button after choosing a network.
3. Press New Pairing and DeepLink button then.
4. Dapp redirects to Kotlin Wallet.
5. Kotlin Wallet get crashed.

**Expected behavior**
Kotlin Wallet does not crash. A session proposal is shown in the wallet.

**Device (please complete the following information):**
 - Device: Any Android device
 - OS: Any Android system

**Comment by seabornlee** [comment]
I have this error also. When I call eth_signTypedData and parse the message crashed the wallet, after restarting the wallet app, it crashed automatically with this exception. Didn't get a place to catch it.

**Comment by jakobuid** [comment]
Hey, a fix for this crash will be available within next release this week.
