### ISSUE TITLE
Array Index out of Bounds exception on Scan dApp

### ISSUE THREAD

**Issue by AbdulRehmanNazar** [WalletConnect/WalletConnectKotlinV2#33]
Hello Walletconnect team,
When I try to connect the walletConnect with dApp I got the exception, here is the log, Please checkout and let me know what I am doing wrong?
Thanks in advance

   java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at org.bouncycastle.math.ec.rfc7748.X25519Field.decode32(Unknown Source:0)
        at org.bouncycastle.math.ec.rfc7748.X25519Field.decode128(Unknown Source:2)
        at org.bouncycastle.math.ec.rfc7748.X25519Field.decode(Unknown Source:1)
        at org.bouncycastle.math.ec.rfc7748.X25519.scalarMult(Unknown Source:11)
        at com.walletconnect.walletconnectv2.crypto.managers.BouncyCastleCryptoManager.generateTopicAndSharedKey-XzpjbtE(BouncyCastleCryptoManager.kt:38)
        at com.walletconnect.walletconnectv2.engine.EngineInteractor.settlePairingSequence-5X_OPRs(EngineInteractor.kt:385)
        at com.walletconnect.walletconnectv2.engine.EngineInteractor.pair$walletconnectv2_release(EngineInteractor.kt:86)
        at com.walletconnect.walletconnectv2.WalletConnectClient.pair(WalletConnectClient.kt:43)
        at com.xigu.sdk_test_demo.MainActivity.pair(MainActivity.java:96)
        at com.xigu.sdk_test_demo.MainActivity.lambda$initScannerResult$0$com-xigu-sdk_test_demo-MainActivity(MainActivity.java:334)
        at com.xigu.sdk_test_demo.MainActivity$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1279)
        at android.app.Activity.performStart(Activity.java:7967)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3364)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by jakobuid** [comment]
Hello, thanks for reporting.
Could you share what dApp you try to connect with?
It seems that the peer key format is wrong when crating the key agreement. The required key size is 256 bits. Pls make sure that it's correct.

**Comment by AbdulRehmanNazar** [comment]
thanks @jakobuid for reaching out and sorry for little late reply, Here is the dApp that I am trying to connect
https://foundation.app

If you have any sample dApp, let me know to give a try to connect?
thanks

**Comment by AbdulRehmanNazar** [comment]
@jakobuid Is there any option where I can get the test wallet configuration to use in the AppMetaData to initialize the WalletConnect SDK in android app?

**Comment by livin-bad** [comment]
@AbdulRehmanNazar https://github.com/WalletConnect/WalletConnectKotlinV2/issues/34#issue-1094986993 
Facing the same issue, any luck on your issue?

**Comment by jakobuid** [comment]
Hey @AbdulRehmanNazar please have a look at: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/34#issuecomment-1007231130.

**WalletConnectKotlinV2** is designed to support the **WalletConnectV2** so any dApp that you try connect with should support the  **WalletConnectV2** as well.

Here you can find the example dApp that you can try: https://react-app.walletconnect.com/

**Comment by AbdulRehmanNazar** [comment]
thanks @jakobuid 
I have tested it and it works fine,I have one question 
other dApps like https://foundation.app what kind of protocols they are using which does not support by walletconnect, because when I see the Connect Wallet there I can see Walletconnect option to connect?
but lib does not support it

**Comment by jakobuid** [comment]
This particular dApp uses the WalletConnect protocol as well. The only difference is the version that they integrated. It's <2.0.
The Kotlin SDK is compatible **only** with the WalletConnect 2.0. WalletConnect v2.0 is **NOT** backwards-compatible with v1.0. Hence, both the wallet and the dApp have to integrate the WalletConnect 2.0 to establish communication over the v2 of the protocol.

**Comment by AbdulRehmanNazar** [comment]
ah, got it
thanks @jakobuid
