### ISSUE TITLE
Crash when the phone language is Turkish

### ISSUE THREAD

**Issue by ditzdragos** [WalletConnect/WalletConnectKotlinV2#470]
**Describe the bug**
When you change the language of the device to Turkish (maybe other languages as well), the DI component crashes at startup.

**SDK Version**
 - Client: Kotlin Wallet Connect Sign
 - Version 2.1.0
 - Client: Kotlin Wallet Connect Core
 - Version 1.3.0

**To Reproduce**
1. Select another language on the testing device
2. Open application
3. See crash

**Expected behavior**
The Wallet Connect SDK initialize correctly

**Device (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 11

**Additional context**
2022-11-07 15:46:12.200 9471-9598 E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
    Process: com.elrond.maiar.wallet.debug, PID: 9471
    org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.walletconnect.android.internal.common.storage.PairingStorageRepositoryInterface']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:173)
        at org.koin.core.Koin.getOrNull(Koin.kt:146)
        at org.koin.core.Koin.getOrNull$default(Koin.kt:142)
        at com.walletconnect.android.pairing.PairingClient$pairingRepository$2.invoke(PairingClient.kt:346)
        at com.walletconnect.android.pairing.PairingClient$pairingRepository$2.invoke(PairingClient.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.walletconnect.android.pairing.PairingClient.getPairingRepository(PairingClient.kt:38)
        at com.walletconnect.android.pairing.PairingClient.access$getPairingRepository(PairingClient.kt:27)
        at com.walletconnect.android.pairing.PairingClient$resubscribeToPairingFlow$2$2$1$1.invokeSuspend(PairingClient.kt:269)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6117dd1, Dispatchers.IO]
    Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.walletconnect.android.impl.storage.data.dao.PairingQueries']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at com.walletconnect.android.impl.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:80)
        at com.walletconnect.android.impl.di.BaseStorageModuleKt$baseStorageModule$1$8.invoke(BaseStorageModule.kt:62)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        	... 26 more
     Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'com.walletconnect.android.impl.core.AndroidCoreDatabase' & qualifier:'android_core_database'. Check your definitions!

**Comment by Elyniss** [comment]
I was unable to reproduce the issue by adding support to Turkish and Polish in our sample apps.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest version :slightly_smiling_face:
