### ISSUE TITLE
All namespaces must be approved

### ISSUE THREAD

**Issue by wds1181977** [WalletConnect/WalletConnectKotlinV2#483]
I run the latest official example kotlin wallet, select multiple chains, and report an error when authorizing. The problem is not found in the comparison/react wallet

`2022-11-16 00:26:39.807 25846-25846/com.walletconnect.wallet E/WalletSessionProposalVi: com.walletconnect.sign.common.exceptions.InvalidNamespaceException: All namespaces must be approved
        at com.walletconnect.sign.engine.domain.SignEngine.approve$sdk_debug(SignEngine.kt:200)
        at com.walletconnect.sign.client.SignProtocol.approveSession(SignProtocol.kt:121)
        at com.walletconnect.sign.client.SignClient.approveSession(Unknown Source:12)
        at com.walletconnect.wallet.ui.host.proposal.SessionProposalViewModel.approve(SessionProposalViewModel.kt:46)
        at com.walletconnect.wallet.ui.host.proposal.SessionProposalBottomSheet.onViewCreated$lambda-2$lambda-1(SessionProposalBottomSheet.kt:50)
        at com.walletconnect.wallet.ui.host.proposal.SessionProposalBottomSheet.$r8$lambda$R4iYKlqLle2bWet6oafY83HYz-U(Unknown Source:0)
        at com.walletconnect.wallet.ui.host.proposal.SessionProposalBottomSheet$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6675)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:6647)
        at android.view.View.access$3100(View.java:791)
        at android.view.View$PerformClick.run(View.java:26339)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7779)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)`

**Comment by jakobuid** [comment]
Hey @wds1181977, thanks for reporting.

The current limitation on the wallet sample causes the issue. We have it on our roadmap to add support for the lacking chains.
