### ISSUE TITLE
Internal errors in Wallet Connect

### ISSUE THREAD

**Issue by XOOPsoft** [WalletConnect/WalletConnectKotlinV2#490]
Sometimes this happens in the onError in SignClient.WalletDelegate.
After this error has occurred it is not possible to get a connection with a dApp again.
If Pair is called later, the onSessionProposal is never coming again.
It doesn't help the kill and relaunch the app.
I have to delete the WalletConnectAndroidCore.db and WalletConnectV2.db to be able to use wallet connect again on the device.

2022-11-17 13:33:37.492 22321-22351 System.out java.lang.InternalError: ChaCha20Poly1305 cannot be reused for encryption	at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$handleError$1.invokeSuspend(JsonRpcInteractor.kt:271)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-11-17 13:33:37.508 22321-22351 System.out java.lang.InternalError: JsonRpcInteractor: Received unknown object type	at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$handleError$1.invokeSuspend(JsonRpcInteractor.kt:271)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-11-17 13:33:37.822 22321-22363 System.out java.lang.InternalError: No PublicKey for tag: 1a852c689fe303c33356d1e2cc6414c4050697d975449e2feb96334dd58294b7	at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$handleError$1.invokeSuspend(JsonRpcInteractor.kt:271)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

And another error:
2022-11-18 08:31:30.541 30133-30251 System.out java.lang.InternalError: Output buffer too short  	at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$handleError$1.invokeSuspend(JsonRpcInteractor.kt:271)  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)  
2022-11-18 08:31:30.541 30133-30251 System.out java.lang.InternalError: Output buffer too short  	at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$handleError$1.invokeSuspend(JsonRpcInteractor.kt:271)  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)  

**SDK Version**
 - Client: Kotlin
 - Version android-core:1.3.0 and sign:2.1.0

**Comment by jakobuid** [comment]
Hey @XOOPsoft, thanks for reporting.

The root cause of your issue is the lack of a symmetric key in the keychain. Could you please provide user flow steps on what you did before receiving the error?

> After this error has occurred it is not possible to get a connection with a dApp again.
> If Pair is called later, the onSessionProposal is never coming again.

I noticed an inconsistency here. To receive the session proposal over the same pairing in your wallet, you should call `SignClient.connect` method from the Dapp. This method is responsible for sending a session proposal over pairing. Once sent successfully, Dapp should expose the pairing URL, which is then consumed by a wallet calling the `pair` method. 

Let me know if this helps.

**Comment by XOOPsoft** [comment]
The connection has already been established when these onError event comes to the SignClient.WalletDelegate.
The flow: First initialise Wallet Connect in App onCreate, setup delegates, pair with QR code, wait for onSessionProposal, when it comes setup approve params and approveSession. Everything goes well. The session has been established and dApp is notified about the approveSession.
Then I am doing nothing in either dApp nor in the Android app. Simply waiting for some time.
I can see from network loggings in the browser of the dApp, that it calls wss://relay.walletconnect.com/?auth=ey...
every 5 minutes and in the Android app i get onConnectionStateChange false, then onConnectionStateChange true - i guess this is to keep the connection alive?
Eventually at some point the android app receives onError event as posted above.
Sometimes it takes 2 minutes until the onError event comes, sometimes 5 minutes or more.
After this error has occurred it is not possible to setup a new connection with the dApp until 5 minutes has passed and the Android app has been relaunched to initialise Wallet Connect again in App onCreate.

**Comment by jakobuid** [comment]
I tried to reproduce the described issue but never succeeded. The connection indeed gets reconnected due to the load rebalancing. However, it shouldn't affect the way how sdk works.

- Did it happen to you once, or can you reproduce it whenever you do the flow above?
- Did it happen to you when a request was received on the wallet or peers were idle?

**Comment by XOOPsoft** [comment]
It has happened several times. But it is not consistently.
I have also ended up in a situation, where it is not possible at all to setup a new session. Even if I kill the wallet app and refresh the browser with the dApp. When I call pair from the wallet with a new code, then the onSessionProposal never comes.
In that case, then the only thing that helps is to delete the WalletConnectAndroidCore.db and WalletConnectV2.db files.
Would it help if you get these two db files and the wc_key_store.xml file ?
Info: Our Android wallet implementation is using the Wallet connect SDK from a background service.

**Comment by jakobuid** [comment]
Can I ask for a code snipped on how you run our SDK? It would be best if your project is opensource, where we can look.

**Comment by XOOPsoft** [comment]
Our project is open source. It can be found here:
https://github.com/Concordium/concordium-reference-wallet-android
Please check out the "WalletConnect" branch and use prodTestNetDebug build variant.
Then it is actually possible for you to create a test wallet with identity and account by using the "Concordium testnet IP" option when you come to the identity creation screen.
We also have a test dApp here:
https://piggybank.testnet.concordium.com/

**Comment by jakobuid** [comment]
Great, let me look into your repo and do some research.

**Comment by jakobuid** [comment]
Hey @XOOPsoft, I managed to provide a solution that improves the reliability of SDK. SDK will work despite of the occurrences of the above errors. It'll be available within the next release.

A couple of observations after digging into your code:
- I noticed when I scan qr code more that once, I see couple of `onSessionProposal` and `onSessionSettleResponse` logs on your side. When I scan 3x I see 3 logs etc. Where SDK exposes only one event, it might be also sth that causes most of your issues.
-  I'm not aware of your usecase but sending ping within every 5s might be redundant. The connection itself is reconnected every 5 mins, which reduce stale connectivity. I recommend increasing the duration of ping, and consider closing the connection when lock screen with pin pops up, which will also help with keeping the connection alive.
- FYI in our SDK we persist all active session, so if you were to use them after restarting your app there's appropriate method for that in our API: `fun getListOfSettledSessions(): List<Sign.Model.Session>` and `fun getSettledSessionByTopic(topic: String): Sign.Model.Session?`
