### ISSUE TITLE
Could not create instance for [Singleton:'com.walletconnect.foundation.network.data.service.RelayService',qualifier:relay_service]

### ISSUE THREAD

**Issue by dinisgt92** [WalletConnect/WalletConnectKotlinV2#491]
**Describe the bug**
Crash in initialization.

**SDK Version**
Client: Kotlin
 Version android-core:1.3.0 and sign:2.1.0

**To Reproduce**
Run in release

**Expected behavior**
No crashes on initialization.

**Device (please complete the following information):**
 - Device: Samsung SM-A520F
 - OS: Android 8.0.0

**Additional context**

U7.c: Could not create instance for [Singleton:'com.walletconnect.foundation.network.data.service.RelayService',qualifier:relay_service]
        at V7.c.a(InstanceFactory.kt:22)
        at V7.d.a(SingleInstanceFactory.kt:2)
        at V7.d$a.invoke(SingleInstanceFactory.kt:2)
        at V7.d.b(SingleInstanceFactory.kt:2)
        at a8.a.d(InstanceRegistry.kt:3)
        at b8.a.g(Scope.kt:6)
        at b8.a.b(Scope.kt:10)
        at com.walletconnect.android.relay.RelayClient.initialize(RelayClient.kt:20)
        at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:2)
        at com.walletconnect.android.CoreClient.initialize$default(Unknown Source:11)
        at Q1.g.onAttachedToActivity(WalletConnectV2Plugin.kt:8)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:13)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:61)
        at java.lang.reflect.Method.invoke(Native Method)
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:4)
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:2)
        at com.example.crypto_wallet.MainActivity.configureFlutterEngine(MainActivity.kt:1)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:8)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:4)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Cannot resolve message adapter for type: class com.walletconnect.foundation.network.model.RelayDTO$Publish$Result$Acknowledgement, annotations: [Ljava.lang.annotation.Annotation;@b32e1db.
        at a4.h.a(MessageAdapterResolver.kt:14)
        at a4.a$b.a(EventMapper.kt:17)
        at a4.i$b$a.a(ServiceMethod.kt:10)
        at a4.j$a.a(ServiceMethodExecutor.kt:17)
        at X3.a$a.a(Service.kt:4)
        at W3.g.b(Scarlet.kt:1)
        at com.walletconnect.android.internal.common.di.NetworkModuleKt$androidApiNetworkModule$1$9.invoke(NetworkModule.kt:4)
        at com.walletconnect.android.internal.common.di.NetworkModuleKt$androidApiNetworkModule$1$9.invoke(NetworkModule.kt:1)
        at V7.c.a(InstanceFactory.kt:10)
        at V7.d.a(SingleInstanceFactory.kt:2) 
        at V7.d$a.invoke(SingleInstanceFactory.kt:2) 
        at V7.d.b(SingleInstanceFactory.kt:2) 
        at a8.a.d(InstanceRegistry.kt:3) 
        at b8.a.g(Scope.kt:6) 
        at b8.a.b(Scope.kt:10) 
        at com.walletconnect.android.relay.RelayClient.initialize(RelayClient.kt:20) 
        at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:2) 
        at com.walletconnect.android.CoreClient.initialize$default(Unknown Source:11) 
        at Q1.g.onAttachedToActivity(WalletConnectV2Plugin.kt:8) 
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:13) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:61) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:4) 
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:2) 
        at com.example.crypto_wallet.MainActivity.configureFlutterEngine(MainActivity.kt:1) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:8) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:4) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: w4.a: 2 exceptions occurred. 
        at a4.h.a(MessageAdapterResolver.kt:11)
        at a4.a$b.a(EventMapper.kt:17) 
        at a4.i$b$a.a(ServiceMethod.kt:10) 
        at a4.j$a.a(ServiceMethodExecutor.kt:17) 
        at X3.a$a.a(Service.kt:4) 
        at W3.g.b(Scarlet.kt:1) 
        at com.walletconnect.android.internal.common.di.NetworkModuleKt$androidApiNetworkModule$1$9.invoke(NetworkModule.kt:4) 
        at com.walletconnect.android.internal.common.di.NetworkModuleKt$androidApiNetworkModule$1$9.invoke(NetworkModule.kt:1) 
        at V7.c.a(InstanceFactory.kt:10) 
        at V7.d.a(SingleInstanceFactory.kt:2) 
        at V7.d$a.invoke(SingleInstanceFactory.kt:2) 
        at V7.d.b(SingleInstanceFactory.kt:2) 
        at a8.a.d(InstanceRegistry.kt:3) 
        at b8.a.g(Scope.kt:6) 
        at b8.a.b(Scope.kt:10) 
        at com.walletconnect.android.relay.RelayClient.initialize(RelayClient.kt:20) 
        at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:2) 
        at com.walletconnect.android.CoreClient.initialize$default(Unknown Source:11) 
        at Q1.g.onAttachedToActivity(WalletConnectV2Plugin.kt:8) 
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:13) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:61) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:4) 
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:2) 
        at com.example.crypto_wallet.MainActivity.configureFlutterEngine(MainActivity.kt:1) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:8) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:4) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: w4.a$a: Chain of Causes for CompositeException In Order Received =>
        at android.util.Log.printlns(Log.java:539)
        at android.util.Log.e(Log.java:331)
        at io.flutter.Log.e(Log.java:2)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:62)
        at java.lang.reflect.Method.invoke(Native Method) 
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:4) 
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:2) 
        at com.example.crypto_wallet.MainActivity.configureFlutterEngine(MainActivity.kt:1) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:8) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:4) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:272)
        at java.lang.Enum$1.create(Enum.java:263)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2414)
        at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at n6.e.<clinit>(JvmPrimitiveType.java:12)
        at n6.e.j(Unknown Source:0)
2022-11-17 15:56:02.387 30809-30809/? E/GeneratedPluginRegistrant:     at G5.c.<clinit>(JavaToKotlinClassMap.kt:73)
        at B5.S.b(RuntimeTypeMapper.kt:9)
        at B5.l.K(KClassImpl.kt:4)
        at B5.l$a$i.invoke(KClassImpl.kt:1)
        at B5.O$a.invoke(ReflectProperties.java:4)
        at B5.l$a.j(KClassImpl.kt:2)
        at B5.l.O(Unknown Source:8)
        at B5.l.isAbstract(Unknown Source:0)
        at P3.b.a(KotlinJsonAdapter.kt:11)
        at com.squareup.moshi.z.e(Moshi.java:29)
        at e4.a$a.a(MoshiMessageAdapter.kt:6)
        at a4.h.a(MessageAdapterResolver.kt:6)
        at a4.a$b.a(EventMapper.kt:17)
        at a4.i$b$a.a(ServiceMethod.kt:10)
        at a4.j$a.a(ServiceMethodExecutor.kt:17)
        at X3.a$a.a(Service.kt:4)
        at W3.g.b(Scarlet.kt:1)
        at com.walletconnect.android.internal.common.di.NetworkModuleKt$androidApiNetworkModule$1$9.invoke(NetworkModule.kt:4)
        at com.walletconnect.android.internal.common.di.NetworkModuleKt$androidApiNetworkModule$1$9.invoke(NetworkModule.kt:1)
        at V7.c.a(InstanceFactory.kt:10)
        at V7.d.a(SingleInstanceFactory.kt:2)
        at V7.d$a.invoke(SingleInstanceFactory.kt:2)
        at V7.d.b(SingleInstanceFactory.kt:2)
        at a8.a.d(InstanceRegistry.kt:3)
        at b8.a.g(Scope.kt:6)
        at b8.a.b(Scope.kt:10)
        at com.walletconnect.android.relay.RelayClient.initialize(RelayClient.kt:20)
        at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:2)
        at com.walletconnect.android.CoreClient.initialize$default(Unknown Source:11)
        at Q1.g.onAttachedToActivity(WalletConnectV2Plugin.kt:8)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:13)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:61)
        	... 18 more
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.Enum$1.create(Enum.java:268)
        	... 59 more
     Caused by: java.lang.IllegalArgumentException: Type is not supported by this MessageAdapterFactory: class com.walletconnect.foundation.network.model.RelayDTO$Publish$Result$Acknowledgement
        at d4.a.a(BuiltInMessageAdapterFactory.kt:4)
        	... 39 more

**Comment by jakobuid** [comment]
Hello @dinisgt92, thanks for reporting. 

Two questions for you:
1.  Do you run your application with the `isMinifyEnabled` set to true?
2. Do you try to use SDK inside the flutter project?

**Comment by dinisgt92** [comment]
Hello.
1. Yes, isMinifyEnabled = true
2. Yes, I use SDK inside the flutter project.

**Comment by jakobuid** [comment]
Your issue is caused by lacking the pro guard rules on our side when the above flag is enabled. We're aware of this and currently working on a solution. See: https://github.com/orgs/WalletConnect/projects/4/views/1?query=is%3Aopen+sort%3Aupdated-desc

This should be available within the next release and hopefully resolves your issue.

**Comment by jakobuid** [comment]
Hey, we released a fix for the above issue, could you confirm if it helps?

**Comment by ludowkm** [comment]
Hello @jakobuid , i still met this issue with the latest SDK: sign:2.5.0 and android-core:1.7.0
And my usecase is similar to @dinisgt92 with isMinifyEnabled = true and using inside the flutter project
Could you please help us to check, thank you!

**Comment by jakobuid** [comment]
Hey @ludowkm unfortunately we didn't test our SDK with Flutter projects, so it's hard to say anything constructive but let's try.
Can you tell me how you initialize SDK? Our recommended way is to do it inside the Android Application class and pass the application to the CoreClient initialization method. Is it sth that you're trying to mimic? 

Are you using Manual or Automatic connection mode?
Are you using our own RelaClient instance?

Are you trying to build a Flutter SDK as a wrapper for Kotlin Sign SDK or are you trying to use our SDK directly in your Flutter project?

**Comment by ludowkm** [comment]
Hello @jakobuid , i followed exact your instruction document to initialize SDK, it worked fine on debug build so its not problem.
Im using manual mode and your own RelayClient instance.
I'm trying to build flutter sdk as a wrapper for kotlin sign sdk.
Everything worked very well on debug build, the issue only happened on release build, so i guess there is something wrong with proguard.
Do you have any idea on it, there is only this remain issue then i can release new support v2 for my wallet app, thank you!

**Comment by jakobuid** [comment]
Thanks for your answer, let me look into that, will come back to you once I have something.

Is your project open source so that I can have a look at your code base? I'm just curious what's current work status on your Flutter SDK, super interesting.

**Comment by ludowkm** [comment]
Hey @jakobuid , thank you for your reply.
I resolved my issue, it's. caused by missing proguard rules when build release, i think it's similar to this current issue so we can close.

**Comment by jakobuid** [comment]
Just to wrap up. Was the issue on your side? If yes, can you share your solution?

**Comment by kackogut** [comment]
Hi @jakubuid we are getting the same error after updating Wallet Connect in Android Native project from `1.5.0` -> `1.9.3`. We have `minifyEnabled` flag set to `true` and we are following initialization based on the documentation

```

Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.walletconnect.foundation.network.data.service.RelayService',qualifier:relay_service]'
  at org.koin.core.instance.InstanceFactory.create(SourceFile:58)
  at org.koin.core.instance.SingleInstanceFactory.create(SourceFile:46)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:53)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:51)
  at org.koin.mp.KoinPlatformTools.synchronized(SourceFile:20)
  at org.koin.core.instance.SingleInstanceFactory.get(SourceFile:51)
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(SourceFile:116)
  at org.koin.core.scope.Scope.resolveValue(SourceFile:246)
  at org.koin.core.scope.Scope.resolveInstance(SourceFile:231)
  at org.koin.core.scope.Scope.get(SourceFile:210)
  at com.walletconnect.android.relay.RelayClient.initialize$sdk_release(SourceFile:133)
  at com.walletconnect.android.CoreClient.initialize(SourceFile:67)
  at com.walletconnect.android.CoreClient.initialize$default(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initializeWalletConnect(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initialize(SourceFile:29)
  at fi.unstoppable.ultimate.android.wallet.external.connect.usecase.InitializeWalletConnectUseCase.execute(SourceFile:13)
  at fi.unstoppable.ultimate.android.UnstoppableApplication.onCreate(SourceFile:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
  at android.app.ActivityThread.access$1200(ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalArgumentException: Receive method must return ParameterizedType: public abstract kotlinx.coroutines.flow.Flow com.walletconnect.foundation.network.data.service.RelayService.observeBatchSubscribeAcknowledgement()
  at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(SourceFile:74)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(SourceFile:66)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.toServiceMethod(SourceFile:47)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.findServiceMethods(SourceFile:38)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.create(SourceFile:32)
  at com.tinder.scarlet.internal.Service$Factory.create(SourceFile:28)
  at com.tinder.scarlet.Scarlet.implementService(SourceFile:108)
  at com.tinder.scarlet.Scarlet.create(SourceFile:100)
  at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$12.invoke(SourceFile:124)
  at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$12.invoke(SourceFile:123)
  at org.koin.core.instance.InstanceFactory.create(SourceFile:51)
  at org.koin.core.instance.SingleInstanceFactory.create(SourceFile:46)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:53)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:51)
  at org.koin.mp.KoinPlatformTools.synchronized(SourceFile:20)
  at org.koin.core.instance.SingleInstanceFactory.get(SourceFile:51)
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(SourceFile:116)
  at org.koin.core.scope.Scope.resolveValue(SourceFile:246)
  at org.koin.core.scope.Scope.resolveInstance(SourceFile:231)
  at org.koin.core.scope.Scope.get(SourceFile:210)
  at com.walletconnect.android.relay.RelayClient.initialize$sdk_release(SourceFile:133)
  at com.walletconnect.android.CoreClient.initialize(SourceFile:67)
  at com.walletconnect.android.CoreClient.initialize$default(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initializeWalletConnect(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initialize(SourceFile:29)
  at fi.unstoppable.ultimate.android.wallet.external.connect.usecase.InitializeWalletConnectUseCase.execute(SourceFile:13)
  at fi.unstoppable.ultimate.android.UnstoppableApplication.onCreate(SourceFile:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
  at android.app.ActivityThread.access$1200(ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```
