### ISSUE TITLE
Correct session request cannot be parsed by the SDK

### ISSUE THREAD

**Issue by kamilargent** [WalletConnect/WalletConnectKotlinV2#513]
**Describe the bug**
When sending a specific session request the client receives an error instead of an actual request.

**SDK Version**
 - Client: Kotlin
 - Version
   - com.walletconnect:android-core:1.5.0
   - com.walletconnect:sign:2.3.0

**To Reproduce**
1. Connect to dapp
2. Initiate the following session request from dapp
```json
{
   "id":1670007177305746,
   "jsonrpc":"2.0",
   "method":"wc_sessionRequest",
   "params":{
      "request":{
         "method":"starknet_requestAddInvokeTransaction",
         "params":{
            "accountAddress":"0x05739743a3d2199e62e1ec0dafa51f031a7605b6c435a93fdc0a6bdad1f2e722",
            "executionRequest":{
               "calls":[
                  {
                     "contractAddress":"0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
                     "calldata":[
                        "2465795642632971912885426363894147890865303766466183163047643963432318986018",
                        "1000000000000000",
                        "0"
                     ],
                     "entrypoint":"transfer"
                  }
               ],
               "invocationDetails":{
                  
               }
            }
         }
      },
      "chainId":"starknet:SNGOERLI"
   }
}
```
3. Observe device

**Expected behavior**
The request is received by the client

**Actual behavior**
The following error is propagated to the delegate

```
java.lang.InternalError: JsonRpcInteractor: Unknown request params
    at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$handleError$1.invokeSuspend(JsonRpcInteractor.kt:287)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```

**Device (please complete the following information):**
 - Device: Asus Zenfone 8
 - OS: Android 12
 - Browser Chrome

**Additional context**
The bug is in `SessionRequestVOJsonAdapter`. The following inner exception is caught:
```
java.lang.IllegalArgumentException: Failed Deserializing Unknown Type 2465795642632971912885426363894147890865303766466183163047643963432318986018
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.upsertArray(SessionRequestVOJsonAdapter.kt:103)
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.upsertObject(SessionRequestVOJsonAdapter.kt:76)
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.upsertArray(SessionRequestVOJsonAdapter.kt:98)
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.upsertObject(SessionRequestVOJsonAdapter.kt:76)
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.upsertObject(SessionRequestVOJsonAdapter.kt:77)
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.fromJson(SessionRequestVOJsonAdapter.kt:54)
    at com.walletconnect.sign.common.adapters.SessionRequestVOJsonAdapter.fromJson(SessionRequestVOJsonAdapter.kt:12)
    at com.walletconnect.sign.common.model.vo.clientsync.session.params.SignParams_SessionRequestParamsJsonAdapter.fromJson(SignParams_SessionRequestParamsJsonAdapter.kt:41)
    at com.walletconnect.sign.common.model.vo.clientsync.session.params.SignParams_SessionRequestParamsJsonAdapter.fromJson(SignParams_SessionRequestParamsJsonAdapter.kt:21)
    at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
    at com.walletconnect.sign.common.model.vo.clientsync.session.SignRpc_SessionRequestJsonAdapter.fromJson(SignRpc_SessionRequestJsonAdapter.kt:67)
    at com.walletconnect.sign.common.model.vo.clientsync.session.SignRpc_SessionRequestJsonAdapter.fromJson(SignRpc_SessionRequestJsonAdapter.kt:25)
    at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
    at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
    at com.walletconnect.android.impl.json_rpc.data.JsonRpcSerializer.tryDeserialize(JsonRpcSerializer.kt:48)
    at com.walletconnect.android.impl.json_rpc.data.JsonRpcSerializer.deserialize(JsonRpcSerializer.kt:24)
    at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor.handleRequest(JsonRpcInteractor.kt:247)
    at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor.manageSubscriptions(JsonRpcInteractor.kt:236)
    at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor.access$manageSubscriptions(JsonRpcInteractor.kt:28)
    at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$manageSubscriptions$1$2.emit(JsonRpcInteractor.kt:230)
    at com.walletconnect.android.impl.json_rpc.domain.JsonRpcInteractor$manageSubscriptions$1$2.emit(JsonRpcInteractor.kt:230)
```

**Comment by TalhaAli00** [comment]
@kamilargent The fix for this has been released, it is available in Sign 2.3.1
