### ISSUE TITLE
JSONException when trying to pair

### ISSUE THREAD

**Issue by Serpivskyi** [WalletConnect/WalletConnectKotlinV2#66]
I trying to pair wallet with wc:b5d84e98-8660-4e34-b82e-2d91b531956c@1?bridge=https%3A%2F%2Fe.bridge.walletconnect.org&key=6ba41ee0dc492234390efb9e42e32cec51c01a638766ca087ff01ca1897a3ce6 (https://app.uniswap.org/) and get this exception. 
Problem in this:
    val relay = JSONObject(mapOfQueryParameters["relay"] ?: "{}").getString("protocol") ?: String.Empty
What am I doing wrong? Or its your mistake?
Process: co.bitfrost, PID: 15004
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: org.json.JSONException: No value for protocol
        at org.json.JSONObject.get(JSONObject.java:399)
        at org.json.JSONObject.getString(JSONObject.java:560)
        at com.walletconnect.walletconnectv2.engine.model.mapper.EngineMapperKt.toPairProposal(EngineMapper.kt:32)
        at com.walletconnect.walletconnectv2.engine.domain.EngineInteractor.pair$walletconnectv2_release(EngineInteractor.kt:121)
        at com.walletconnect.walletconnectv2.client.WalletConnectClient.pair(WalletConnectClient.kt:80)
        at co.bitfrost.other.connect.WalletConnectManager.pairConnection(WalletConnectManager.kt:60)
        at co.bitfrost.presentation.ui.fragments.main.wallet.WalletFragment$setupClickListeners$1$3$1.invoke(WalletFragment.kt:95)
        at co.bitfrost.presentation.ui.fragments.main.wallet.WalletFragment$setupClickListeners$1$3$1.invoke(WalletFragment.kt:127)
        at co.bitfrost.presentation.ui.dialogs.QRScannerDialog.handleResult(QRScannerDialog.kt:131)
        at me.dm7.barcodescanner.zxing.ZXingScannerView$1.run(ZXingScannerView.java:164)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)

**Comment by jakobuid** [comment]
Hey @Serpivskyi thanks for reporting.
The reason why you get the above exception is that `https://app.uniswap.org/` has WalletConnectV1 integrated. Our SDK is WalletConnectV2 compatible. If you want to test the SDK you can do it with: https://react-app.walletconnect.com/

WalletConnect v2.0 is NOT backwards-compatible with v1.0.

**Comment by Serpivskyi** [comment]
So I have to use the first version of the api (https://github.com/WalletConnect/kotlin-walletconnect-lib)?

**Comment by Serpivskyi** [comment]
And if I integrate V1 realization, it will be compatible with the V2?

**Comment by Serpivskyi** [comment]
https://react-app.walletconnect.com/, button disabled(

**Comment by jakobuid** [comment]
- if you want to use V1: wallet and dapp should integrate v1
- if you want to use V2: wallet and dapp should integrate V2

There is no cross compatibility. 
First you have to choose the network to enable the button. When you press connect the modal with qr should will be shown.
