### ISSUE TITLE
SDK crashes during intialization on Android 7

### ISSUE THREAD

**Issue by kamilargent** [WalletConnect/WalletConnectKotlinV2#689]
**Describe the bug**
SDK crashes during initialization on Android 7 due to not `java/util/Base64` not being found

**SDK Version**
 - Client: Android
 - Version: BOM 1.6.0

**To Reproduce**
1. Install app using Web3Wallet SDK on a device with Android 7 (API 24)
2. Initialize SDK

**Expected behavior**
SDK initializes successfully

**Device (please complete the following information):**
 - Device: Redmi Note 4
 - OS: Android 7 

It's also reproducible on emulators.

**Additional context**

`java.util.Base64` is only available on Android starting with API level 26. On older Android versions `android.util.Base64` needs to be used.

**Stacktrace**
> Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
       at com.walletconnect.foundation.util.jwt.JwtUtilsKt.encodeBase64(JwtUtils.kt:40)
       at com.walletconnect.foundation.util.jwt.JwtUtilsKt.encodeJSON(JwtUtils.kt:35)
       at com.walletconnect.foundation.util.jwt.JwtHeader.<init>(JwtHeader.kt:17)
       at com.walletconnect.foundation.util.jwt.JwtHeader.<clinit>(JwtHeader.kt:20)
       at com.walletconnect.foundation.crypto.data.repository.BaseClientIdJwtRepository.generateJWT(BaseClientIdJwtRepository.kt:35)
       at com.walletconnect.android.internal.common.jwt.GenerateJwtStoreClientIdUseCase.invoke(GenerateJwtStoreClientIdUseCase.kt:14)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$1.invoke(CoreNetworkModule.kt:35)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$1.invoke(CoreNetworkModule.kt:34)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
       at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:106)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.java:133)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:98)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:99)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:99)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:100)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:101)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:102)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$10.invoke(CoreNetworkModule.kt:96)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:106)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.java:133)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$11.invoke(CoreNetworkModule.kt:107)
       at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$11.invoke(CoreNetworkModule.kt:106)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:106)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.java:133)
       at com.walletconnect.android.relay.RelayClient.initialize$sdk_release(RelayClient.kt:29)
       at com.walletconnect.android.relay.RelayClient.initialize$sdk_release(RelayClient.kt:32)
       at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:58)

**Comment by TalhaAli00** [comment]
Resolved issue by switching to MultiBase's implementation
