### ISSUE TITLE
Too many follow-up requests

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/WalletConnectKotlinV2#703]

**Comment by jakubuid** [comment]
Summary after Trust and WalletConnect call:
Connectivity issues cannot be reproduced on either WC’s or Trust’s sides. A developer from Trust will collect logs and reach back out to us if he sees it again

**Comment by XuanYuan1122** [comment]
CoreClient.Error
com.walletconnect.android.internal.common.exception.GenericException: Too many follow-up requests: 21
                                                                                                    	at com.walletconnect.android.utils.ExtensionsKt.getToWalletConnectException(Extensions.kt:47)
                                                                                                    	at com.walletconnect.android.relay.RelayClient$collectConnectionErrors$$inlined$map$1$2.emit(Emitters.kt:224)
                                                                                                    	at com.walletconnect.android.relay.RelayClient$collectConnectionErrors$$inlined$filterIsInstance$1$2.emit(Emitters.kt:224)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:224)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
