### ISSUE TITLE
CoreClient initialization fails for some users

### ISSUE THREAD

**Issue by kamilargent** [WalletConnect/WalletConnectKotlinV2#849]
**Describe the bug**
For some users, the SDK initialization fails. The exact reproduction steps are unknown. It looks like some DI issue.

**SDK Version**
 - Client: Android BOM
 - Version 1.9.2

**To Reproduce**
1. Initialize the SDK

**Expected behavior**
Initialization is successful

**Device (please complete the following information):**
Issue occurs on various devices & SDK versions.

**Additional context**
```
Failed to initialize the sdk: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.walletconnect.android.sync.engine.domain.SyncEngine']'
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:106)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.kt:133)
       at com.walletconnect.android.sync.client.SyncProtocol.initialize(SyncProtocol.kt:37)
       at com.walletconnect.android.sync.client.SyncClient.initialize(SyncClient.kt)
       at com.walletconnect.android.CoreClient.initialize(CoreClient.kt:71)
       at com.walletconnect.android.CoreClient.initialize$default(CoreClient.kt:37)
```

**Comment by Elyniss** [comment]
Thanks for submitting the issue! We will create a new release once we merge #850
