### ISSUE TITLE
Crash on initialization for obfuscated release version

### ISSUE THREAD

**Issue by kackogut** [WalletConnect/WalletConnectKotlinV2#861]
**Describe the bug**
Crash when initializing Wallet Connect

**SDK Version**
 - Client: Kotlin
 - Version: BOM: 1.9.3, android-core, web3wallet
 - Kotlin version: `1.8.21`
 - Coroutines version: `1.6.4`
 - Gradle plugin: `8.0.1`
 - Gradle version `8.1.1`

**To Reproduce**
1. Follow docs to initialize WalletConnect
2. Turn on obsufication with `minifyEnabled = true`
3. Launch the app

**Expected behavior**
Wallet Connect initialized correctly on release builds

**Device (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13

**Additional context**
Might be connected to closed issue: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/491#issuecomment-1541634262

We spotted the issue when upgrading from BOM version `1.5.0` to `1.9.3`

Logs:
```
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.walletconnect.foundation.network.data.service.RelayService',qualifier:relay_service]'
  at org.koin.core.instance.InstanceFactory.create(SourceFile:58)
  at org.koin.core.instance.SingleInstanceFactory.create(SourceFile:46)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:53)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:51)
  at org.koin.mp.KoinPlatformTools.synchronized(SourceFile:20)
  at org.koin.core.instance.SingleInstanceFactory.get(SourceFile:51)
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(SourceFile:116)
  at org.koin.core.scope.Scope.resolveValue(SourceFile:246)
  at org.koin.core.scope.Scope.resolveInstance(SourceFile:231)
  at org.koin.core.scope.Scope.get(SourceFile:210)
  at com.walletconnect.android.relay.RelayClient.initialize$sdk_release(SourceFile:133)
  at com.walletconnect.android.CoreClient.initialize(SourceFile:67)
  at com.walletconnect.android.CoreClient.initialize$default(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initializeWalletConnect(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initialize(SourceFile:29)
  at fi.unstoppable.ultimate.android.wallet.external.connect.usecase.InitializeWalletConnectUseCase.execute(SourceFile:13)
  at fi.unstoppable.ultimate.android.UnstoppableApplication.onCreate(SourceFile:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
  at android.app.ActivityThread.access$1200(ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalArgumentException: Receive method must return ParameterizedType: public abstract kotlinx.coroutines.flow.Flow com.walletconnect.foundation.network.data.service.RelayService.observeBatchSubscribeAcknowledgement()
  at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(SourceFile:74)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(SourceFile:66)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.toServiceMethod(SourceFile:47)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.findServiceMethods(SourceFile:38)
  at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.create(SourceFile:32)
  at com.tinder.scarlet.internal.Service$Factory.create(SourceFile:28)
  at com.tinder.scarlet.Scarlet.implementService(SourceFile:108)
  at com.tinder.scarlet.Scarlet.create(SourceFile:100)
  at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$12.invoke(SourceFile:124)
  at com.walletconnect.android.internal.common.di.CoreNetworkModuleKt$coreAndroidNetworkModule$1$12.invoke(SourceFile:123)
  at org.koin.core.instance.InstanceFactory.create(SourceFile:51)
  at org.koin.core.instance.SingleInstanceFactory.create(SourceFile:46)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:53)
  at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SourceFile:51)
  at org.koin.mp.KoinPlatformTools.synchronized(SourceFile:20)
  at org.koin.core.instance.SingleInstanceFactory.get(SourceFile:51)
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(SourceFile:116)
  at org.koin.core.scope.Scope.resolveValue(SourceFile:246)
  at org.koin.core.scope.Scope.resolveInstance(SourceFile:231)
  at org.koin.core.scope.Scope.get(SourceFile:210)
  at com.walletconnect.android.relay.RelayClient.initialize$sdk_release(SourceFile:133)
  at com.walletconnect.android.CoreClient.initialize(SourceFile:67)
  at com.walletconnect.android.CoreClient.initialize$default(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initializeWalletConnect(SourceFile:37)
  at fi.unstoppable.ultimate.android.wallet.external.connect.walletConnect.DefaultWalletConnectWrapper.initialize(SourceFile:29)
  at fi.unstoppable.ultimate.android.wallet.external.connect.usecase.InitializeWalletConnectUseCase.execute(SourceFile:13)
  at fi.unstoppable.ultimate.android.UnstoppableApplication.onCreate(SourceFile:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
  at android.app.ActivityThread.access$1200(ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

**Comment by jakubuid** [comment]
@kackogut Are you using your own RelayClient (RelayConnectionInterface) instance?
Can you please show your code snipped where you initialize the SDK?

**Comment by kackogut** [comment]
I think we are not using RelayClient instance. I just noticed that downgrading to version `1.5.0` poroduces the same error, so I guess it's related to the Kotlin, Gradle plugin or other update. I added our versions in the issue description, if you need any other version please let me know. Here's the initialization:

```
    private fun initializeWalletConnect() {
        CoreClient.initialize(
            relayServerUrl = serverUrl,
            connectionType = connectionType,
            application = application,
            metaData = getAppMetaData(),
            onError = { error ->
                Timber.i("### Error WalletConnect initialization: $error")
            }
        )

        val initParams = Wallet.Params.Init(core = CoreClient)

        Web3Wallet.initialize(
            params = initParams,
            onError = { error ->
                Timber.i("### Error WalletConnect initialization: $error")
            }
        )
    }

    private fun getAppMetaData(): Core.Model.AppMetaData {
        return Core.Model.AppMetaData(
            name = application.getString(ResourcesR.string.app_name),
            // TODO: pass description
            description = "",
            url = "...",
            icons = listOf(appIconUrl),
            // TODO: Pass URl if needed
            redirect = "..."
        )
    }

    private companion object {
        const val projectId = ...
        const val relayUrl = "relay.walletconnect.com"
        const val serverUrl = "wss://$relayUrl?projectId=$projectId"
        const val appIconUrl = "..."
        val connectionType = ConnectionType.AUTOMATIC
    }
```

**Comment by jakubuid** [comment]
Thank you, I'm investigating

**Comment by jakubuid** [comment]
@kackogut Is your initialization logic inside the onCreate of Application class?

**Comment by longht021189** [comment]
Hi, my project is stuck at this, too. Do you have any resolution?

The app crash at com.tinder.scarlet.internal.servicemethod.ServiceMethod.Companion#requireReturnTypeIsOneOf
`private inline fun Method.requireReturnTypeIsOneOf(vararg types: Class<*>, lazyMessage: () -> Any) = require(types.any { it === genericReturnType || it.isInstance(genericReturnType) }, lazyMessage)
`

So, I check genericReturnType value and this is result:
- Without Proguard: It was class libcore.reflect.ParameterizedTypeImpl
- With Proguard: It was interface kotlinx.coroutines.flow.Flow

And ParameterizedType is not match in Proguard mode

**Comment by jakubuid** [comment]
@kackogut have you been able to find the solution on your side?
We've been heads down on some other issues, @longht021189 let me re-investigate it

**Comment by TalhaAli00** [comment]
@kackogut are you using R8 full mode?

**Comment by kackogut** [comment]
@jakubuid unfortunately no luck on our side so far

@TalhaAli00 we are not using full R8 mode

**Comment by jakubuid** [comment]
@kackogut FYI - We've been able to reproduce your issue - now we're working on the fix
