### ISSUE TITLE
Samples Dapp Demo crashes when connecting to the Android emulator: Creating Pairing failed, No connection available

### ISSUE THREAD

**Issue by kangkaislove** [WalletConnect/WalletConnectKotlinV2#912]
**Describe the bug**
When using the Android emulator to run the Samples Dapp Demo for initializing connection nodes, it consistently crashes

**SDK Version**
 - Client:  Kotlin
 - Version BOM1.10.0

**To Reproduce**
1. Open wc Dapp
2. Select ethereum
3. Click connect
4. See crash

**Expected behavior**
Samples Dapp Demo can be run on the android emulator.

**Screenshots**
[SVID-2023-06-05-162855.webm](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/12255740/31ee132a-fa1a-42d7-90bc-4e597ac7e83f)

**Device (please complete the following information):**
 - Device: Android Emulator Pixel 4 x86 
 - OS: Android 11
 
**Additional context**
`Process: com.walletconnect.sample.dapp, PID: 13983
java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: com.walletconnect.android.internal.common.exception.NoRelayConnectionException: No connection available
                                                                                                    	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.checkConnectionWorking(JsonRpcInteractor.kt:57)
                                                                                                    	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.subscribe(JsonRpcInteractor.kt:225)
                                                                                                    	at com.walletconnect.android.internal.common.model.type.JsonRpcInteractorInterface$DefaultImpls.subscribe$default(JsonRpcInteractorInterface.kt:17)
                                                                                                    	at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:118)
                                                                                                    	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:42)
                                                                                                    	at com.walletconnect.sample.dapp.ui.routes.composable_routes.chain_selection.ChainSelectionViewModel.connectToWallet(ChainSelectionViewModel.kt:53)
                                                                                                    	at com.walletconnect.sample.dapp.ui.routes.composable_routes.chain_selection.ChainSelectionViewModel.connectToWallet$default(ChainSelectionViewModel.kt:49)
                                                                                                    	at com.walletconnect.sample.dapp.ui.routes.composable_routes.chain_selection.ChainSelectionRouteKt$ChainSelectionRoute$4.invoke(ChainSelectionRoute.kt:93)
                                                                                                    	at com.walletconnect.sample.dapp.ui.routes.composable_routes.chain_selection.ChainSelectionRouteKt$ChainSelectionRoute$4.invoke(ChainSelectionRoute.kt:83)
                                                                                                    	at com.walletconnect.sample_common.ui.commons.ButtonsKt$BlueButton$1$1.invoke(Buttons.kt:27)
                                                                                                    	at com.walletconnect.sample_common.ui.commons.ButtonsKt$BlueButton$1$1.invoke(Buttons.kt:26)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:898)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:892)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:670)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:546)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:568)
                                                                                                    	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:858)
                                                                                                    	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:706)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:96)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1376)`

**Comment by jakubuid** [comment]
Hey @kangkaislove thanks for reporting. Can you share where are you based? It might be connected to what you see
