### ISSUE TITLE
[Bug] samples.dapp always crash when it call pushRequest.

### ISSUE THREAD

**Issue by nhatpv-1627** [WalletConnect/WalletConnectKotlinV2#942]
**Describe the bug**
I'm running examples of this repo: `samples.dapp` and `sample.wallet`. 
I've added google-services.json and done paring them successfully as in the picture below. 
Then I tap the Push request button, the app immediately crashes below: 

```
FATAL EXCEPTION: main
Process: com.walletconnect.sample.dapp, PID: 9212
 java.util.NoSuchElementException: Collection contains no element matching the predicate.
at com.walletconnect.sample.dapp.ui.routes.composable_routes.session.SessionViewModel.pushRequest(SessionViewModel.kt:173)
at com.walletconnect.sample.dapp.ui.routes.composable_routes.session.SessionRouteKt$SessionRoute$6.invoke(SessionRoute.kt:76)
at com.walletconnect.sample.dapp.ui.routes.composable_routes.session.SessionRouteKt$SessionRoute$6.invoke(SessionRoute.kt:76)
at com.walletconnect.sample_common.ui.commons.ButtonsKt$BlueButton$1$1.invoke(Buttons.kt:27)
at com.walletconnect.sample_common.ui.commons.ButtonsKt$BlueButton$1$1.invoke(Buttons.kt:26)
at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
```
I've checked and found out that SignClient.getListOfActiveSessions() always be empty.
Please help to check. Did I miss any config?

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
1. Run samples.dapp and sample.wallet 
2. Connect(pair) dapp with wallet 
3. Pair successfully then click to Request push button
4. See the error

**Expected behavior**
Send Request push to the wallet to approve. Then Dapp can Notify to Wallet

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/43597747/b26646f8-a2cf-4d74-b9ea-7e5c9aa4c021)

**Additional context**

**Comment by nhatpv-1627** [comment]
By the way, I've tried to add FCM API key to [Console](https://cloud.walletconnect.com/app/project) . But It's not finished.
After debugging, I found that there was an error in this API:

![image](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/43597747/689c5d24-122f-4823-b671-04ee30f616b6)

![image](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/43597747/f43df8c6-30f0-4914-a078-343f25d74e26)
![image](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/43597747/a02259f9-149c-48e2-b608-49fc01a73630)
Please help to check!

**Comment by nhatpv-1627** [comment]
Another issue, the WalletApp approves Request Push from Dapp successfully in UI, but I found the error in Logcat here:

```
java.lang.Throwable: {"status":"FAILURE","error":{"name":"cacao","message":"Unable to verify"},"value":null} at com.walletconnect.android.keyserver.domain.use_case.UtilsKt.unwrapUnit(Utils.kt:17) at com.walletconnect.android.keyserver.domain.use_case.RegisterIdentityUseCase.invoke-gIAlu-s(RegisterIdentityUseCase.kt:11) at com.walletconnect.android.keyserver.domain.use_case.RegisterIdentityUseCase$invoke$1.invokeSuspend(Unknown Source:12) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```
So I think the WalletApp approved Request Push from Dapp failed actually!

**Comment by arein** [comment]
@TalhaAli00 can you pls take a look?
