### ISSUE TITLE
Samples.dapp crashes when selecting any chain other than Etherium

### ISSUE THREAD

**Issue by Raenar4k** [WalletConnect/WalletConnectKotlinV2#955]
**Describe the bug**
Samples.dapp crashes when selecting any chain other than Etherium

**SDK Version**
 - Client: Kotlin
 - Version: Sample latest on 8a98b63592c943ed0fe7c5b01a671fd468f9a58d

**To Reproduce**
1. Run sample.dapp
2. Click on any chain other then Etherium. (I want to test on Polygon Mumbai)
3. Crash

```
Process: com.walletconnect.sample.dapp, PID: 19717
java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
at com.walletconnect.sample.dapp.ui.routes.bottom_routes.PairingSelectionViewModel$special$$inlined$map$2$2.emit(Emitters.kt:224)
at com.walletconnect.sample.dapp.ui.routes.bottom_routes.PairingSelectionViewModel$special$$inlined$map$1$2.emit(Emitters.kt:223)
at kotlinx.coroutines.flow.FlowKt__BuildersKt$flowOf$$inlined$unsafeFlow$2.collect(SafeCollector.common.kt:113)
at com.walletconnect.sample.dapp.ui.routes.bottom_routes.PairingSelectionViewModel$special$$inlined$map$1.collect(SafeCollector.common.kt:113)
at com.walletconnect.sample.dapp.ui.routes.bottom_routes.PairingSelectionViewModel$special$$inlined$map$2.collect(SafeCollector.common.kt:113)
```

**Expected behavior**
Sample works same way as if Etherium network is selected

**Device:**
 - Device: Pixel 7 pro
 - OS: Android 13
 - Version: latest on 8a98b63592c943ed0fe7c5b01a671fd468f9a58d

**Additional context**

**Comment by duybuikardiachain** [comment]
You tested on Metamask? 
On Pairing, have a line of code:
`it.icons.first() to it.name`, try to use `it.url to it.name` will solve your issue

**Comment by Raenar4k** [comment]
I didnt even get to step to deeplink to any app. It crashes when selecting chain in sample
